window.FATIGA_DATA = {
 "actualizado": "29/09/2026 08:51",
 "periodo": "2026-09-01 a 2026-09-29",
 "diagnostico": [
  {
   "cuenta": "San Juan del Rio",
   "adset": "Publicación: \"Atención zona San Juan del Río. 📍\"",
   "veredicto": "RENOVAR PUBLICO",
   "freq": 2.37,
   "gasto": 10783,
   "leads": 231,
   "cpl": 47,
   "pct_nuevos": 18,
   "cpm1": 30,
   "cpm2": 33
  },
  {
   "cuenta": "Promo/Compl.",
   "adset": "Publicación: \"¿Vives con dolor en Ecatepec? 📍\"",
   "veredicto": "RENOVAR PUBLICO",
   "freq": 2.3,
   "gasto": 55705,
   "leads": 917,
   "cpl": 61,
   "pct_nuevos": 19,
   "cpm1": 40,
   "cpm2": 40
  },
  {
   "cuenta": "Promo/Compl.",
   "adset": "Publicación: \"¡Que el dolor no te apague el grito este...\"",
   "veredicto": "RENOVAR PUBLICO",
   "freq": 2.17,
   "gasto": 14826,
   "leads": 249,
   "cpl": 60,
   "pct_nuevos": 19,
   "cpm1": 66,
   "cpm2": 80
  },
  {
   "cuenta": "Valle Dorado",
   "adset": "NEUROPATIA",
   "veredicto": "PUBLICO CANSANDOSE",
   "freq": 2.12,
   "gasto": 3445,
   "leads": 55,
   "cpl": 63,
   "pct_nuevos": 35,
   "cpm1": 47,
   "cpm2": 68
  },
  {
   "cuenta": "Promo/Compl.",
   "adset": "Publicación: \"¿Dolor de espalda al agacharte?\"",
   "veredicto": "PUBLICO CANSANDOSE",
   "freq": 2.05,
   "gasto": 14361,
   "leads": 242,
   "cpl": 59,
   "pct_nuevos": 23,
   "cpm1": 27,
   "cpm2": 38
  },
  {
   "cuenta": "Ajusco",
   "adset": "ESP",
   "veredicto": "PUBLICO CANSANDOSE",
   "freq": 1.8,
   "gasto": 4411,
   "leads": 66,
   "cpl": 67,
   "pct_nuevos": 21,
   "cpm1": 58,
   "cpm2": 95
  },
  {
   "cuenta": "Tepeyac",
   "adset": "MIX",
   "veredicto": "PUBLICO CANSANDOSE",
   "freq": 1.77,
   "gasto": 3156,
   "leads": 82,
   "cpl": 38,
   "pct_nuevos": 34,
   "cpm1": 23,
   "cpm2": 33
  },
  {
   "cuenta": "Claveria",
   "adset": "NEUROPATIA - CHECK",
   "veredicto": "PUBLICO CANSANDOSE",
   "freq": 1.7,
   "gasto": 2276,
   "leads": 75,
   "cpl": 30,
   "pct_nuevos": 13,
   "cpm1": 50,
   "cpm2": 72
  },
  {
   "cuenta": "Satelite",
   "adset": "RODILLA - CHECK",
   "veredicto": "PUBLICO CANSANDOSE",
   "freq": 1.4,
   "gasto": 5762,
   "leads": 166,
   "cpl": 35,
   "pct_nuevos": 16,
   "cpm1": 34,
   "cpm2": 43
  },
  {
   "cuenta": "Laura (sedes)",
   "adset": "ESPALDA",
   "veredicto": "CAMBIAR CREATIVO",
   "freq": 3.55,
   "gasto": 42279,
   "leads": 1692,
   "cpl": 25,
   "pct_nuevos": 342,
   "cpm1": 27,
   "cpm2": 23
  },
  {
   "cuenta": "Promo/Compl.",
   "adset": "Publicación: \"📍 ¿Vives en Milpa Alta y el dolor de rodilla ya...\"",
   "veredicto": "CAMBIAR CREATIVO",
   "freq": 3.21,
   "gasto": 41549,
   "leads": 844,
   "cpl": 49,
   "pct_nuevos": 65,
   "cpm1": 22,
   "cpm2": 25
  },
  {
   "cuenta": "Nicolas Romero",
   "adset": "Publicación: \"¡Atención, Nicolás Romero! ¿Buscas terapia de...\"",
   "veredicto": "CAMBIAR CREATIVO",
   "freq": 3.11,
   "gasto": 20824,
   "leads": 366,
   "cpl": 57,
   "pct_nuevos": 47,
   "cpm1": 28,
   "cpm2": 30
  },
  {
   "cuenta": "Promo/Compl.",
   "adset": "Publicación: \"En Equilibrio Total seguimos creciendo y buscamos...\"",
   "veredicto": "CAMBIAR CREATIVO",
   "freq": 3.06,
   "gasto": 3247,
   "leads": 30,
   "cpl": 108,
   "pct_nuevos": null,
   "cpm1": null,
   "cpm2": null
  },
  {
   "cuenta": "Cuautla",
   "adset": "Publicación: \"¿Te duele el hombro, la espalda o la rodilla? 😖\"",
   "veredicto": "CAMBIAR CREATIVO",
   "freq": 3.05,
   "gasto": 14669,
   "leads": 464,
   "cpl": 32,
   "pct_nuevos": 40,
   "cpm1": 19,
   "cpm2": 24
  },
  {
   "cuenta": "Queretaro",
   "adset": "NEUROPATIA",
   "veredicto": "CAMBIAR CREATIVO",
   "freq": 2.97,
   "gasto": 4478,
   "leads": 254,
   "cpl": 18,
   "pct_nuevos": 43,
   "cpm1": 51,
   "cpm2": 44
  },
  {
   "cuenta": "Laura (sedes)",
   "adset": "Neuropatia",
   "veredicto": "CAMBIAR CREATIVO",
   "freq": 2.85,
   "gasto": 3736,
   "leads": 77,
   "cpl": 49,
   "pct_nuevos": 275,
   "cpm1": 31,
   "cpm2": 30
  },
  {
   "cuenta": "Laura (sedes)",
   "adset": "Rodilla",
   "veredicto": "CAMBIAR CREATIVO",
   "freq": 2.83,
   "gasto": 4031,
   "leads": 92,
   "cpl": 44,
   "pct_nuevos": 411,
   "cpm1": 25,
   "cpm2": 25
  },
  {
   "cuenta": "Pachuca",
   "adset": "NEUROPATÍA",
   "veredicto": "CAMBIAR CREATIVO",
   "freq": 2.8,
   "gasto": 1850,
   "leads": 42,
   "cpl": 44,
   "pct_nuevos": 75,
   "cpm1": 39,
   "cpm2": 46
  },
  {
   "cuenta": "San Juan del Rio",
   "adset": "Neuropatia - Check",
   "veredicto": "CAMBIAR CREATIVO",
   "freq": 2.78,
   "gasto": 1084,
   "leads": 27,
   "cpl": 40,
   "pct_nuevos": 82,
   "cpm1": 37,
   "cpm2": 37
  },
  {
   "cuenta": "Promo/Compl.",
   "adset": "Publicación: \"Si eres de Plaza Neza, 📍\"",
   "veredicto": "CAMBIAR CREATIVO",
   "freq": 2.75,
   "gasto": 37286,
   "leads": 764,
   "cpl": 49,
   "pct_nuevos": 53,
   "cpm1": 35,
   "cpm2": 37
  },
  {
   "cuenta": "Queretaro",
   "adset": "RODILLA",
   "veredicto": "CAMBIAR CREATIVO",
   "freq": 2.6,
   "gasto": 635,
   "leads": 42,
   "cpl": 15,
   "pct_nuevos": 24,
   "cpm1": 50,
   "cpm2": 56
  },
  {
   "cuenta": "Cuautla",
   "adset": "Neuropatia",
   "veredicto": "CAMBIAR CREATIVO",
   "freq": 2.55,
   "gasto": 3496,
   "leads": 145,
   "cpl": 24,
   "pct_nuevos": 55,
   "cpm1": 25,
   "cpm2": 27
  },
  {
   "cuenta": "Ajusco",
   "adset": "NEU",
   "veredicto": "CAMBIAR CREATIVO",
   "freq": 2.53,
   "gasto": 3919,
   "leads": 68,
   "cpl": 58,
   "pct_nuevos": 96,
   "cpm1": 67,
   "cpm2": 89
  },
  {
   "cuenta": "Laura (sedes)",
   "adset": "Servicios / Testimonios",
   "veredicto": "CAMBIAR CREATIVO",
   "freq": 2.5,
   "gasto": 1657,
   "leads": 27,
   "cpl": 61,
   "pct_nuevos": 146,
   "cpm1": 29,
   "cpm2": 35
  },
  {
   "cuenta": "Cuautla",
   "adset": "Rodilla",
   "veredicto": "VIGILAR",
   "freq": 2.5,
   "gasto": 842,
   "leads": 25,
   "cpl": 34,
   "pct_nuevos": 46,
   "cpm1": 31,
   "cpm2": 31
  },
  {
   "cuenta": "Laura (sedes)",
   "adset": "RODILLA",
   "veredicto": "VIGILAR",
   "freq": 2.48,
   "gasto": 4413,
   "leads": 174,
   "cpl": 25,
   "pct_nuevos": 434,
   "cpm1": 60,
   "cpm2": 40
  },
  {
   "cuenta": "Promo/Compl.",
   "adset": "Publicación: \"El dolor articular no desaparece solo. Actúa y...\"",
   "veredicto": "VIGILAR",
   "freq": 2.44,
   "gasto": 21684,
   "leads": 364,
   "cpl": 60,
   "pct_nuevos": 50,
   "cpm1": 32,
   "cpm2": 39
  },
  {
   "cuenta": "Ajusco",
   "adset": "ROD",
   "veredicto": "VIGILAR",
   "freq": 2.43,
   "gasto": 8015,
   "leads": 109,
   "cpl": 74,
   "pct_nuevos": 60,
   "cpm1": 56,
   "cpm2": 67
  },
  {
   "cuenta": "Promo/Compl.",
   "adset": "Publicación: \"Si eres de Mixquiahuala Hidalgo, 📍\"",
   "veredicto": "VIGILAR",
   "freq": 2.42,
   "gasto": 11163,
   "leads": 293,
   "cpl": 38,
   "pct_nuevos": 77,
   "cpm1": 24,
   "cpm2": 23
  },
  {
   "cuenta": "San Juan del Rio",
   "adset": "Publicación: \"🏥 Conoce Equilibrio Total San Juan del Río, tu...\"",
   "veredicto": "VIGILAR",
   "freq": 2.4,
   "gasto": 5562,
   "leads": 191,
   "cpl": 29,
   "pct_nuevos": 270,
   "cpm1": 35,
   "cpm2": 26
  },
  {
   "cuenta": "Cuautitlan",
   "adset": "Directo",
   "veredicto": "VIGILAR",
   "freq": 2.4,
   "gasto": 13678,
   "leads": 732,
   "cpl": 19,
   "pct_nuevos": 65,
   "cpm1": 36,
   "cpm2": 45
  },
  {
   "cuenta": "Laura (sedes)",
   "adset": "Publico Nuevo (radio 10km, edad 22-65)",
   "veredicto": "VIGILAR",
   "freq": 2.37,
   "gasto": 3164,
   "leads": 83,
   "cpl": 38,
   "pct_nuevos": 267,
   "cpm1": 25,
   "cpm2": 31
  },
  {
   "cuenta": "Promo/Compl.",
   "adset": "Publicación: \"En Equilibrio Total seguimos creciendo y buscamos...\"",
   "veredicto": "VIGILAR",
   "freq": 2.37,
   "gasto": 2776,
   "leads": 36,
   "cpl": 77,
   "pct_nuevos": null,
   "cpm1": null,
   "cpm2": null
  },
  {
   "cuenta": "Nicolas Romero",
   "adset": "RODILLA",
   "veredicto": "VIGILAR",
   "freq": 2.36,
   "gasto": 7688,
   "leads": 245,
   "cpl": 31,
   "pct_nuevos": 40,
   "cpm1": 21,
   "cpm2": 22
  },
  {
   "cuenta": "Laura (sedes)",
   "adset": "NEUROPATIA",
   "veredicto": "VIGILAR",
   "freq": 2.33,
   "gasto": 13508,
   "leads": 441,
   "cpl": 31,
   "pct_nuevos": 127,
   "cpm1": 42,
   "cpm2": 39
  },
  {
   "cuenta": "Laura (sedes)",
   "adset": "NEUROPATIA",
   "veredicto": "VIGILAR",
   "freq": 2.32,
   "gasto": 6948,
   "leads": 173,
   "cpl": 40,
   "pct_nuevos": 38,
   "cpm1": 32,
   "cpm2": 35
  },
  {
   "cuenta": "Laura (sedes)",
   "adset": "Hombro",
   "veredicto": "VIGILAR",
   "freq": 2.3,
   "gasto": 8732,
   "leads": 221,
   "cpl": 40,
   "pct_nuevos": 154,
   "cpm1": 27,
   "cpm2": 30
  },
  {
   "cuenta": "Pachuca",
   "adset": "RODILLA",
   "veredicto": "VIGILAR",
   "freq": 2.3,
   "gasto": 4578,
   "leads": 122,
   "cpl": 38,
   "pct_nuevos": 42,
   "cpm1": 32,
   "cpm2": 32
  },
  {
   "cuenta": "Nicolas Romero",
   "adset": "ESPALDA",
   "veredicto": "VIGILAR",
   "freq": 2.29,
   "gasto": 4178,
   "leads": 67,
   "cpl": 62,
   "pct_nuevos": 42,
   "cpm1": 25,
   "cpm2": 29
  },
  {
   "cuenta": "Nicolas Romero",
   "adset": "HOMBRO",
   "veredicto": "VIGILAR",
   "freq": 2.25,
   "gasto": 8988,
   "leads": 386,
   "cpl": 23,
   "pct_nuevos": 52,
   "cpm1": 23,
   "cpm2": 21
  },
  {
   "cuenta": "Tepeyac",
   "adset": "Espalda",
   "veredicto": "VIGILAR",
   "freq": 2.21,
   "gasto": 8180,
   "leads": 266,
   "cpl": 31,
   "pct_nuevos": 92,
   "cpm1": 63,
   "cpm2": 78
  }
 ],
 "exitosos": [
  {
   "cuenta": "Xochimilco",
   "ad": "Publicación: \"🌿 En Equilibrio Total Xochimilco llevamos años...\"",
   "adset": "Publicación: \"🌿 En Equilibrio Total Xochimilco llevamos años...\"",
   "freq": 1.44,
   "gasto": 1956,
   "leads": 177,
   "cpl": 11
  },
  {
   "cuenta": "Promo/Compl.",
   "ad": "Neuropatia",
   "adset": "ORGANICO PAUTA",
   "freq": 1.88,
   "gasto": 12927,
   "leads": 956,
   "cpl": 14
  },
  {
   "cuenta": "Promo/Compl.",
   "ad": "Neuropatia",
   "adset": "ORGANICO PAUTA",
   "freq": 1.55,
   "gasto": 5762,
   "leads": 380,
   "cpl": 15
  },
  {
   "cuenta": "Promo/Compl.",
   "ad": "VID - NEURO PADECIMIENTO - OCT",
   "adset": "Neuropatia",
   "freq": 1.54,
   "gasto": 866,
   "leads": 57,
   "cpl": 15
  },
  {
   "cuenta": "Cuautitlan",
   "ad": "VID _ NEUROPATIA  01 ABRIL - Copia",
   "adset": "Directo",
   "freq": 1.34,
   "gasto": 858,
   "leads": 58,
   "cpl": 15
  },
  {
   "cuenta": "Queretaro",
   "ad": "VID - HOMBRO IRVIN",
   "adset": "HOMBRO",
   "freq": 1.54,
   "gasto": 3844,
   "leads": 238,
   "cpl": 16
  },
  {
   "cuenta": "Promo/Compl.",
   "ad": "VID - ACUPUNTURA JUN",
   "adset": "ORGANICO PAUTA",
   "freq": 1.76,
   "gasto": 2659,
   "leads": 145,
   "cpl": 18
  },
  {
   "cuenta": "Queretaro",
   "ad": "VID - HOMBRO DOLOROSO JUN",
   "adset": "HOMBRO",
   "freq": 1.5,
   "gasto": 1303,
   "leads": 72,
   "cpl": 18
  },
  {
   "cuenta": "Cuautitlan",
   "ad": "VID_QUIRO _ 1 ABRIL - Copia 2",
   "adset": "Directo",
   "freq": 1.27,
   "gasto": 1176,
   "leads": 67,
   "cpl": 18
  },
  {
   "cuenta": "Promo/Compl.",
   "ad": "Neuropatia - Copia",
   "adset": "PROMOCIONES CDMX",
   "freq": 1.53,
   "gasto": 10930,
   "leads": 577,
   "cpl": 19
  },
  {
   "cuenta": "Gerontologia",
   "ad": "VID_CONSULTA_GE _ NUEVO - Copia",
   "adset": "Coacalco",
   "freq": 1.69,
   "gasto": 2511,
   "leads": 134,
   "cpl": 19
  },
  {
   "cuenta": "Claveria",
   "ad": "VID _ PADECIMIENTO RODILLA _ OCT",
   "adset": "RODILLA - CHECK",
   "freq": 1.45,
   "gasto": 2328,
   "leads": 107,
   "cpl": 22
  },
  {
   "cuenta": "Laura (sedes)",
   "ad": "EST - NEUROPATIA V3 JUL",
   "adset": "NEUROPATIA",
   "freq": 1.89,
   "gasto": 981,
   "leads": 42,
   "cpl": 23
  },
  {
   "cuenta": "Gerontologia",
   "ad": "VID_CONSULTA_GE _ NUEVO",
   "adset": "Balbuena",
   "freq": 1.89,
   "gasto": 4753,
   "leads": 206,
   "cpl": 23
  },
  {
   "cuenta": "Valle Dorado",
   "ad": "VID _ PADECIMIENTO _ SEP",
   "adset": "HOMBRO",
   "freq": 1.6,
   "gasto": 3317,
   "leads": 146,
   "cpl": 23
  },
  {
   "cuenta": "Laura (sedes)",
   "ad": "VID  _ NEUROPATIA DIABETICA _ OCT",
   "adset": "Neuropatia",
   "freq": 1.9,
   "gasto": 2962,
   "leads": 121,
   "cpl": 24
  },
  {
   "cuenta": "Promo/Compl.",
   "ad": "VID - ACUPUNTURA JUN",
   "adset": "ORGANICO PAUTA",
   "freq": 1.6,
   "gasto": 1984,
   "leads": 81,
   "cpl": 24
  },
  {
   "cuenta": "Satelite",
   "ad": "VID _ NEUROPARITA GENERAL _ OCT",
   "adset": "NEUROPATIA",
   "freq": 1.52,
   "gasto": 791,
   "leads": 33,
   "cpl": 24
  },
  {
   "cuenta": "La Moderna",
   "ad": "VID_ ESPALDA SINTOMAS _SEP",
   "adset": "Espalda",
   "freq": 1.45,
   "gasto": 2130,
   "leads": 88,
   "cpl": 24
  },
  {
   "cuenta": "Laura (sedes)",
   "ad": "VID - NEUROPATIA DIABETICA 3 JUN",
   "adset": "NEUROPATIA",
   "freq": 1.49,
   "gasto": 569,
   "leads": 23,
   "cpl": 25
  },
  {
   "cuenta": "Promo/Compl.",
   "ad": "FEED",
   "adset": "PROMOCIONES CDMX",
   "freq": 1.6,
   "gasto": 18117,
   "leads": 712,
   "cpl": 25
  },
  {
   "cuenta": "Pachuca",
   "ad": "Anuncio Campaña de mensajes personalizada 8/8/2026",
   "adset": "Conjunto de anuncios Campaña de mensajes personalizada 8/8/2026",
   "freq": 1.94,
   "gasto": 15281,
   "leads": 614,
   "cpl": 25
  },
  {
   "cuenta": "Laura (sedes)",
   "ad": "VID _ NEUROPATIA DIABETICA _ OCT",
   "adset": "NEUROPATIA",
   "freq": 1.49,
   "gasto": 3419,
   "leads": 130,
   "cpl": 26
  },
  {
   "cuenta": "Cuautla",
   "ad": "VID - ESPALDA GABO V1 JUN",
   "adset": "Espalda",
   "freq": 1.65,
   "gasto": 860,
   "leads": 33,
   "cpl": 26
  },
  {
   "cuenta": "Gerontologia",
   "ad": "VID_CONSULTA_GE _ NUEVO",
   "adset": "Gero Consulta funcional previa",
   "freq": 1.52,
   "gasto": 827,
   "leads": 31,
   "cpl": 27
  }
 ],
 "sin_leads": []
};
