window.OPTIMIZACION_DATA = {
 "actualizado": "21/09/2026 10:40",
 "periodo": "2026-09-14 a 2026-09-20 (7 días) + fatiga mes en curso (2026-09-01 a 2026-09-21)",
 "items": [
  {
   "clinica": "Promo/Compl.",
   "grupo": "sede",
   "campana": "",
   "adset": "Publicación: \"¡Que el dolor no te apague el grito este...\"",
   "anuncio": "",
   "campaign_id": "",
   "adset_id": "",
   "ad_id": "",
   "gasto_7d": 12604,
   "resultados_7d": 210,
   "costo_resultado": 60,
   "tipo_resultado": "lead",
   "frecuencia": 2.07,
   "pct_nuevos": 18,
   "diagnostico": "PÚBLICO QUEMADO",
   "accion_sugerida": "CAMBIAR PÚBLICO",
   "detalle": "Fatiga por frecuencia (2.07x), periodo mes en curso (2026-09-01 a 2026-09-21).",
   "nivel_accion": "AD SET",
   "formato_actual": "IMAGEN",
   "formato_sugerido": null
  },
  {
   "clinica": "Promo/Compl.",
   "grupo": "sede",
   "campana": "",
   "adset": "Publicación: \"📍 ¿Vives en Milpa Alta y el dolor de rodilla ya...\"",
   "anuncio": "",
   "campaign_id": "",
   "adset_id": "",
   "ad_id": "",
   "gasto_7d": 26524,
   "resultados_7d": 572,
   "costo_resultado": 46,
   "tipo_resultado": "lead",
   "frecuencia": 2.92,
   "pct_nuevos": 46,
   "diagnostico": "CONTENIDO QUEMADO (alta frecuencia)",
   "accion_sugerida": "APAGAR Y PEDIR CONTENIDO NUEVO",
   "detalle": "Fatiga por frecuencia (2.92x), periodo mes en curso (2026-09-01 a 2026-09-21).",
   "nivel_accion": "AD SET",
   "formato_actual": "OTRO",
   "formato_sugerido": "video (formato más eficiente del proyecto, CPL/CPR muy por debajo del resto)"
  },
  {
   "clinica": "Nicolas Romero",
   "grupo": "franquicia",
   "campana": "",
   "adset": "Publicación: \"¡Atención, Nicolás Romero! ¿Buscas terapia de...\"",
   "anuncio": "",
   "campaign_id": "",
   "adset_id": "",
   "ad_id": "",
   "gasto_7d": 14806,
   "resultados_7d": 255,
   "costo_resultado": 58,
   "tipo_resultado": "lead",
   "frecuencia": 2.7,
   "pct_nuevos": 53,
   "diagnostico": "CONTENIDO QUEMADO (alta frecuencia)",
   "accion_sugerida": "APAGAR Y PEDIR CONTENIDO NUEVO",
   "detalle": "Fatiga por frecuencia (2.7x), periodo mes en curso (2026-09-01 a 2026-09-21).",
   "nivel_accion": "AD SET",
   "formato_actual": "OTRO",
   "formato_sugerido": "video (formato más eficiente del proyecto, CPL/CPR muy por debajo del resto)"
  },
  {
   "clinica": "Laura (sedes)",
   "grupo": "sede",
   "campana": "",
   "adset": "ESPALDA",
   "anuncio": "",
   "campaign_id": "",
   "adset_id": "",
   "ad_id": "",
   "gasto_7d": 14524,
   "resultados_7d": 635,
   "costo_resultado": 23,
   "tipo_resultado": "lead",
   "frecuencia": 2.55,
   "pct_nuevos": 119,
   "diagnostico": "CONTENIDO QUEMADO (alta frecuencia)",
   "accion_sugerida": "APAGAR Y PEDIR CONTENIDO NUEVO",
   "detalle": "Fatiga por frecuencia (2.55x), periodo mes en curso (2026-09-01 a 2026-09-21).",
   "nivel_accion": "AD SET",
   "formato_actual": "OTRO",
   "formato_sugerido": "video (formato más eficiente del proyecto, CPL/CPR muy por debajo del resto)"
  },
  {
   "clinica": "Cuautla",
   "grupo": "franquicia",
   "campana": "",
   "adset": "Publicación: \"¿Te duele el hombro, la espalda o la rodilla? 😖\"",
   "anuncio": "",
   "campaign_id": "",
   "adset_id": "",
   "ad_id": "",
   "gasto_7d": 10216,
   "resultados_7d": 382,
   "costo_resultado": 27,
   "tipo_resultado": "lead",
   "frecuencia": 2.58,
   "pct_nuevos": 53,
   "diagnostico": "CONTENIDO QUEMADO (alta frecuencia)",
   "accion_sugerida": "APAGAR Y PEDIR CONTENIDO NUEVO",
   "detalle": "Fatiga por frecuencia (2.58x), periodo mes en curso (2026-09-01 a 2026-09-21).",
   "nivel_accion": "AD SET",
   "formato_actual": "OTRO",
   "formato_sugerido": "video (formato más eficiente del proyecto, CPL/CPR muy por debajo del resto)"
  },
  {
   "clinica": "Queretaro",
   "grupo": "franquicia",
   "campana": "",
   "adset": "NEUROPATIA",
   "anuncio": "",
   "campaign_id": "",
   "adset_id": "",
   "ad_id": "",
   "gasto_7d": 3359,
   "resultados_7d": 177,
   "costo_resultado": 19,
   "tipo_resultado": "lead",
   "frecuencia": 2.65,
   "pct_nuevos": 80,
   "diagnostico": "CONTENIDO QUEMADO (alta frecuencia)",
   "accion_sugerida": "APAGAR Y PEDIR CONTENIDO NUEVO",
   "detalle": "Fatiga por frecuencia (2.65x), periodo mes en curso (2026-09-01 a 2026-09-21).",
   "nivel_accion": "AD SET",
   "formato_actual": "OTRO",
   "formato_sugerido": "video (formato más eficiente del proyecto, CPL/CPR muy por debajo del resto)"
  },
  {
   "clinica": "Promo/Compl.",
   "grupo": "sede",
   "campana": "",
   "adset": "Publicación: \"En Equilibrio Total seguimos creciendo y buscamos...\"",
   "anuncio": "",
   "campaign_id": "",
   "adset_id": "",
   "ad_id": "",
   "gasto_7d": 3299,
   "resultados_7d": 63,
   "costo_resultado": 52,
   "tipo_resultado": "lead",
   "frecuencia": 2.53,
   "pct_nuevos": 1252,
   "diagnostico": "CONTENIDO QUEMADO (alta frecuencia)",
   "accion_sugerida": "APAGAR Y PEDIR CONTENIDO NUEVO",
   "detalle": "Fatiga por frecuencia (2.53x), periodo mes en curso (2026-09-01 a 2026-09-21).",
   "nivel_accion": "AD SET",
   "formato_actual": "OTRO",
   "formato_sugerido": "video (formato más eficiente del proyecto, CPL/CPR muy por debajo del resto)"
  },
  {
   "clinica": "Pachuca",
   "grupo": "franquicia",
   "campana": "",
   "adset": "NEUROPATÍA",
   "anuncio": "",
   "campaign_id": "",
   "adset_id": "",
   "ad_id": "",
   "gasto_7d": 1256,
   "resultados_7d": 31,
   "costo_resultado": 41,
   "tipo_resultado": "lead",
   "frecuencia": 2.58,
   "pct_nuevos": 60,
   "diagnostico": "CONTENIDO QUEMADO (alta frecuencia)",
   "accion_sugerida": "APAGAR Y PEDIR CONTENIDO NUEVO",
   "detalle": "Fatiga por frecuencia (2.58x), periodo mes en curso (2026-09-01 a 2026-09-21).",
   "nivel_accion": "AD SET",
   "formato_actual": "OTRO",
   "formato_sugerido": "video (formato más eficiente del proyecto, CPL/CPR muy por debajo del resto)"
  },
  {
   "clinica": "Queretaro",
   "grupo": "franquicia",
   "campana": "Publicación: \"¿Dolor de espalda, hombro o rodilla? 😣\"",
   "adset": "Publicación: \"¿Dolor de espalda, hombro o rodilla? 😣\"",
   "anuncio": "Publicación: \"¿Dolor de espalda, hombro o rodilla? 😣\"",
   "campaign_id": "52597549831525",
   "adset_id": "52597549834325",
   "ad_id": "52597549845525",
   "gasto_7d": 1596.03,
   "resultados_7d": 29,
   "costo_resultado": 55.04,
   "tipo_resultado": "lead",
   "frecuencia": 1.76,
   "pct_nuevos": null,
   "diagnostico": "CPL/CPR ALTO (targeting o creativo débil, no es fatiga)",
   "accion_sugerida": "APAGAR o BAJAR PRESUPUESTO",
   "detalle": "Costo por resultado 1.9x el promedio de Queretaro ($28) en los últimos 7 días, con frecuencia baja (1.76x) — no es fatiga, el problema es targeting/creativo desde el inicio.",
   "nivel_accion": "CAMPAÑA (CBO, reasigna si solo pausas 1 anuncio)",
   "formato_actual": "OTRO",
   "formato_sugerido": null
  },
  {
   "clinica": "Laura (sedes)",
   "grupo": "sede",
   "campana": "",
   "adset": "Publicación: \"¿Vives en la zona de Tláhuac y el dolor ya forma...\"",
   "anuncio": "",
   "campaign_id": "",
   "adset_id": "",
   "ad_id": "",
   "gasto_7d": 7987,
   "resultados_7d": 102,
   "costo_resultado": 78,
   "tipo_resultado": "lead",
   "frecuencia": 1.88,
   "pct_nuevos": 31,
   "diagnostico": "PÚBLICO CANSÁNDOSE",
   "accion_sugerida": "VIGILAR — preparar cambio de público en los próximos días",
   "detalle": "Fatiga por frecuencia (1.88x), periodo mes en curso (2026-09-01 a 2026-09-21).",
   "nivel_accion": "AD SET",
   "formato_actual": "OTRO",
   "formato_sugerido": null
  },
  {
   "clinica": "Laura (sedes)",
   "grupo": "sede",
   "campana": "",
   "adset": "VIDEO AJUSCO",
   "anuncio": "",
   "campaign_id": "",
   "adset_id": "",
   "ad_id": "",
   "gasto_7d": 7938,
   "resultados_7d": 137,
   "costo_resultado": 58,
   "tipo_resultado": "lead",
   "frecuencia": 1.47,
   "pct_nuevos": 24,
   "diagnostico": "PÚBLICO CANSÁNDOSE",
   "accion_sugerida": "VIGILAR — preparar cambio de público en los próximos días",
   "detalle": "Fatiga por frecuencia (1.47x), periodo mes en curso (2026-09-01 a 2026-09-21).",
   "nivel_accion": "AD SET",
   "formato_actual": "VIDEO",
   "formato_sugerido": null
  },
  {
   "clinica": "Promo/Compl.",
   "grupo": "sede",
   "campana": "",
   "adset": "Publicación: \"¿Te duele el hombro, la espalda o la rodilla?\"",
   "anuncio": "",
   "campaign_id": "",
   "adset_id": "",
   "ad_id": "",
   "gasto_7d": 4379,
   "resultados_7d": 69,
   "costo_resultado": 63,
   "tipo_resultado": "lead",
   "frecuencia": 1.78,
   "pct_nuevos": 25,
   "diagnostico": "PÚBLICO CANSÁNDOSE",
   "accion_sugerida": "VIGILAR — preparar cambio de público en los próximos días",
   "detalle": "Fatiga por frecuencia (1.78x), periodo mes en curso (2026-09-01 a 2026-09-21).",
   "nivel_accion": "AD SET",
   "formato_actual": "OTRO",
   "formato_sugerido": null
  },
  {
   "clinica": "Promo/Compl.",
   "grupo": "sede",
   "campana": "",
   "adset": "Publicación: \"Si eres de Plaza Neza, 📍\"",
   "anuncio": "",
   "campaign_id": "",
   "adset_id": "",
   "ad_id": "",
   "gasto_7d": 25025,
   "resultados_7d": 530,
   "costo_resultado": 47,
   "tipo_resultado": "lead",
   "frecuencia": 2.37,
   "pct_nuevos": 47,
   "diagnostico": "FRECUENCIA SUBIENDO",
   "accion_sugerida": "VIGILAR — sin acción todavía",
   "detalle": "Fatiga por frecuencia (2.37x), periodo mes en curso (2026-09-01 a 2026-09-21).",
   "nivel_accion": "AD SET",
   "formato_actual": "OTRO",
   "formato_sugerido": null
  },
  {
   "clinica": "Laura (sedes)",
   "grupo": "sede",
   "campana": "",
   "adset": "NEUROPATIA",
   "anuncio": "",
   "campaign_id": "",
   "adset_id": "",
   "ad_id": "",
   "gasto_7d": 6657,
   "resultados_7d": 160,
   "costo_resultado": 42,
   "tipo_resultado": "lead",
   "frecuencia": 2.27,
   "pct_nuevos": 71,
   "diagnostico": "FRECUENCIA SUBIENDO",
   "accion_sugerida": "VIGILAR — sin acción todavía",
   "detalle": "Fatiga por frecuencia (2.27x), periodo mes en curso (2026-09-01 a 2026-09-21).",
   "nivel_accion": "AD SET",
   "formato_actual": "OTRO",
   "formato_sugerido": null
  },
  {
   "clinica": "Cuautla",
   "grupo": "franquicia",
   "campana": "",
   "adset": "Neuropatia",
   "anuncio": "",
   "campaign_id": "",
   "adset_id": "",
   "ad_id": "",
   "gasto_7d": 2599,
   "resultados_7d": 106,
   "costo_resultado": 25,
   "tipo_resultado": "lead",
   "frecuencia": 2.32,
   "pct_nuevos": 87,
   "diagnostico": "FRECUENCIA SUBIENDO",
   "accion_sugerida": "VIGILAR — sin acción todavía",
   "detalle": "Fatiga por frecuencia (2.32x), periodo mes en curso (2026-09-01 a 2026-09-21).",
   "nivel_accion": "AD SET",
   "formato_actual": "OTRO",
   "formato_sugerido": null
  },
  {
   "clinica": "Laura (sedes)",
   "grupo": "sede",
   "campana": "",
   "adset": "RODILLA",
   "anuncio": "",
   "campaign_id": "",
   "adset_id": "",
   "ad_id": "",
   "gasto_7d": 2398,
   "resultados_7d": 101,
   "costo_resultado": 24,
   "tipo_resultado": "lead",
   "frecuencia": 2.23,
   "pct_nuevos": 379,
   "diagnostico": "FRECUENCIA SUBIENDO",
   "accion_sugerida": "VIGILAR — sin acción todavía",
   "detalle": "Fatiga por frecuencia (2.23x), periodo mes en curso (2026-09-01 a 2026-09-21).",
   "nivel_accion": "AD SET",
   "formato_actual": "OTRO",
   "formato_sugerido": null
  },
  {
   "clinica": "Laura (sedes)",
   "grupo": "sede",
   "campana": "",
   "adset": "Neuropatia",
   "anuncio": "",
   "campaign_id": "",
   "adset_id": "",
   "ad_id": "",
   "gasto_7d": 2058,
   "resultados_7d": 53,
   "costo_resultado": 39,
   "tipo_resultado": "lead",
   "frecuencia": 2.36,
   "pct_nuevos": 213,
   "diagnostico": "FRECUENCIA SUBIENDO",
   "accion_sugerida": "VIGILAR — sin acción todavía",
   "detalle": "Fatiga por frecuencia (2.36x), periodo mes en curso (2026-09-01 a 2026-09-21).",
   "nivel_accion": "AD SET",
   "formato_actual": "OTRO",
   "formato_sugerido": null
  },
  {
   "clinica": "Ajusco",
   "grupo": "franquicia",
   "campana": "",
   "adset": "NEU",
   "anuncio": "",
   "campaign_id": "",
   "adset_id": "",
   "ad_id": "",
   "gasto_7d": 1998,
   "resultados_7d": 33,
   "costo_resultado": 61,
   "tipo_resultado": "lead",
   "frecuencia": 2.38,
   "pct_nuevos": 43,
   "diagnostico": "FRECUENCIA SUBIENDO",
   "accion_sugerida": "VIGILAR — sin acción todavía",
   "detalle": "Fatiga por frecuencia (2.38x), periodo mes en curso (2026-09-01 a 2026-09-21).",
   "nivel_accion": "AD SET",
   "formato_actual": "OTRO",
   "formato_sugerido": null
  },
  {
   "clinica": "Laura (sedes)",
   "grupo": "sede",
   "campana": "",
   "adset": "Rodilla",
   "anuncio": "",
   "campaign_id": "",
   "adset_id": "",
   "ad_id": "",
   "gasto_7d": 1449,
   "resultados_7d": 43,
   "costo_resultado": 34,
   "tipo_resultado": "lead",
   "frecuencia": 2.3,
   "pct_nuevos": 158,
   "diagnostico": "FRECUENCIA SUBIENDO",
   "accion_sugerida": "VIGILAR — sin acción todavía",
   "detalle": "Fatiga por frecuencia (2.3x), periodo mes en curso (2026-09-01 a 2026-09-21).",
   "nivel_accion": "AD SET",
   "formato_actual": "OTRO",
   "formato_sugerido": null
  },
  {
   "clinica": "Laura (sedes)",
   "grupo": "sede",
   "campana": "",
   "adset": "Servicios / Testimonios",
   "anuncio": "",
   "campaign_id": "",
   "adset_id": "",
   "ad_id": "",
   "gasto_7d": 997,
   "resultados_7d": 17,
   "costo_resultado": 59,
   "tipo_resultado": "lead",
   "frecuencia": 2.2,
   "pct_nuevos": 101,
   "diagnostico": "FRECUENCIA SUBIENDO",
   "accion_sugerida": "VIGILAR — sin acción todavía",
   "detalle": "Fatiga por frecuencia (2.2x), periodo mes en curso (2026-09-01 a 2026-09-21).",
   "nivel_accion": "AD SET",
   "formato_actual": "IMAGEN",
   "formato_sugerido": null
  },
  {
   "clinica": "San Juan del Rio",
   "grupo": "franquicia",
   "campana": "",
   "adset": "Neuropatia - Check",
   "anuncio": "",
   "campaign_id": "",
   "adset_id": "",
   "ad_id": "",
   "gasto_7d": 686,
   "resultados_7d": 19,
   "costo_resultado": 36,
   "tipo_resultado": "lead",
   "frecuencia": 2.42,
   "pct_nuevos": 65,
   "diagnostico": "FRECUENCIA SUBIENDO",
   "accion_sugerida": "VIGILAR — sin acción todavía",
   "detalle": "Fatiga por frecuencia (2.42x), periodo mes en curso (2026-09-01 a 2026-09-21).",
   "nivel_accion": "AD SET",
   "formato_actual": "OTRO",
   "formato_sugerido": null
  },
  {
   "clinica": "Cuautla",
   "grupo": "franquicia",
   "campana": "",
   "adset": "Rodilla",
   "anuncio": "",
   "campaign_id": "",
   "adset_id": "",
   "ad_id": "",
   "gasto_7d": 602,
   "resultados_7d": 21,
   "costo_resultado": 29,
   "tipo_resultado": "lead",
   "frecuencia": 2.22,
   "pct_nuevos": 35,
   "diagnostico": "FRECUENCIA SUBIENDO",
   "accion_sugerida": "VIGILAR — sin acción todavía",
   "detalle": "Fatiga por frecuencia (2.22x), periodo mes en curso (2026-09-01 a 2026-09-21).",
   "nivel_accion": "AD SET",
   "formato_actual": "OTRO",
   "formato_sugerido": null
  },
  {
   "clinica": "Queretaro",
   "grupo": "franquicia",
   "campana": "",
   "adset": "RODILLA",
   "anuncio": "",
   "campaign_id": "",
   "adset_id": "",
   "ad_id": "",
   "gasto_7d": 546,
   "resultados_7d": 37,
   "costo_resultado": 15,
   "tipo_resultado": "lead",
   "frecuencia": 2.47,
   "pct_nuevos": 64,
   "diagnostico": "FRECUENCIA SUBIENDO",
   "accion_sugerida": "VIGILAR — sin acción todavía",
   "detalle": "Fatiga por frecuencia (2.47x), periodo mes en curso (2026-09-01 a 2026-09-21).",
   "nivel_accion": "AD SET",
   "formato_actual": "OTRO",
   "formato_sugerido": null
  },
  {
   "clinica": "Promo/Compl.",
   "grupo": "sede",
   "campana": "",
   "adset": "FUNCIONALES 10",
   "anuncio": "FUNCIONALES 1",
   "campaign_id": "",
   "adset_id": "",
   "ad_id": "",
   "gasto_7d": 14850,
   "resultados_7d": 651,
   "costo_resultado": 23,
   "tipo_resultado": "lead",
   "frecuencia": 1.62,
   "pct_nuevos": null,
   "diagnostico": "RINDE BIEN",
   "accion_sugerida": "ESCALAR — subir presupuesto",
   "detalle": "Frecuencia baja (1.62x) + costo/resultado mejor que su cuenta + volumen decente.",
   "nivel_accion": "AD SET",
   "formato_actual": "OTRO",
   "formato_sugerido": null
  },
  {
   "clinica": "Pachuca",
   "grupo": "franquicia",
   "campana": "",
   "adset": "Conjunto de anuncios Campaña de mensajes personalizada 8/8/2026",
   "anuncio": "Anuncio Campaña de mensajes personalizada 8/8/2026",
   "campaign_id": "",
   "adset_id": "",
   "ad_id": "",
   "gasto_7d": 12031,
   "resultados_7d": 501,
   "costo_resultado": 24,
   "tipo_resultado": "lead",
   "frecuencia": 1.76,
   "pct_nuevos": null,
   "diagnostico": "RINDE BIEN",
   "accion_sugerida": "ESCALAR — subir presupuesto",
   "detalle": "Frecuencia baja (1.76x) + costo/resultado mejor que su cuenta + volumen decente.",
   "nivel_accion": "AD SET",
   "formato_actual": "OTRO",
   "formato_sugerido": null
  },
  {
   "clinica": "Promo/Compl.",
   "grupo": "sede",
   "campana": "",
   "adset": "PROMOCIONES CDMX",
   "anuncio": "FEED",
   "campaign_id": "",
   "adset_id": "",
   "ad_id": "",
   "gasto_7d": 8168,
   "resultados_7d": 346,
   "costo_resultado": 24,
   "tipo_resultado": "lead",
   "frecuencia": 1.4,
   "pct_nuevos": null,
   "diagnostico": "RINDE BIEN",
   "accion_sugerida": "ESCALAR — subir presupuesto",
   "detalle": "Frecuencia baja (1.4x) + costo/resultado mejor que su cuenta + volumen decente.",
   "nivel_accion": "AD SET",
   "formato_actual": "OTRO",
   "formato_sugerido": null
  },
  {
   "clinica": "Promo/Compl.",
   "grupo": "sede",
   "campana": "",
   "adset": "ORGANICO PAUTA",
   "anuncio": "Neuropatia",
   "campaign_id": "",
   "adset_id": "",
   "ad_id": "",
   "gasto_7d": 6631,
   "resultados_7d": 534,
   "costo_resultado": 12,
   "tipo_resultado": "lead",
   "frecuencia": 1.78,
   "pct_nuevos": null,
   "diagnostico": "RINDE BIEN",
   "accion_sugerida": "ESCALAR — subir presupuesto",
   "detalle": "Frecuencia baja (1.78x) + costo/resultado mejor que su cuenta + volumen decente.",
   "nivel_accion": "AD SET",
   "formato_actual": "OTRO",
   "formato_sugerido": null
  },
  {
   "clinica": "Cuautitlan",
   "grupo": "franquicia",
   "campana": "",
   "adset": "Directo",
   "anuncio": "EST _ HERNIA V4 _ 14 MAY -",
   "campaign_id": "",
   "adset_id": "",
   "ad_id": "",
   "gasto_7d": 6568,
   "resultados_7d": 342,
   "costo_resultado": 19,
   "tipo_resultado": "lead",
   "frecuencia": 1.98,
   "pct_nuevos": null,
   "diagnostico": "RINDE BIEN",
   "accion_sugerida": "ESCALAR — subir presupuesto",
   "detalle": "Frecuencia baja (1.98x) + costo/resultado mejor que su cuenta + volumen decente.",
   "nivel_accion": "AD SET",
   "formato_actual": "IMAGEN",
   "formato_sugerido": null
  },
  {
   "clinica": "Nicolas Romero",
   "grupo": "franquicia",
   "campana": "",
   "adset": "HOMBRO",
   "anuncio": "VID_HOMBNICO_JUL",
   "campaign_id": "",
   "adset_id": "",
   "ad_id": "",
   "gasto_7d": 6231,
   "resultados_7d": 285,
   "costo_resultado": 22,
   "tipo_resultado": "lead",
   "frecuencia": 1.9,
   "pct_nuevos": null,
   "diagnostico": "RINDE BIEN",
   "accion_sugerida": "ESCALAR — subir presupuesto",
   "detalle": "Frecuencia baja (1.9x) + costo/resultado mejor que su cuenta + volumen decente.",
   "nivel_accion": "AD SET",
   "formato_actual": "VIDEO",
   "formato_sugerido": null
  },
  {
   "clinica": "Promo/Compl.",
   "grupo": "sede",
   "campana": "",
   "adset": "Publicación: \"En Equilibrio Total La Moderna (Iztacalco),...\"",
   "anuncio": "Publicación: \"En Equilibrio Total La Moderna (Iztacalco),...\"",
   "campaign_id": "",
   "adset_id": "",
   "ad_id": "",
   "gasto_7d": 5491,
   "resultados_7d": 217,
   "costo_resultado": 25,
   "tipo_resultado": "lead",
   "frecuencia": 1.44,
   "pct_nuevos": null,
   "diagnostico": "RINDE BIEN",
   "accion_sugerida": "ESCALAR — subir presupuesto",
   "detalle": "Frecuencia baja (1.44x) + costo/resultado mejor que su cuenta + volumen decente.",
   "nivel_accion": "AD SET",
   "formato_actual": "OTRO",
   "formato_sugerido": null
  },
  {
   "clinica": "Cuautla",
   "grupo": "franquicia",
   "campana": "",
   "adset": "Publicación: \"Vivir con dolor no es normal. 🛑\"",
   "anuncio": "Publicación: \"Vivir con dolor no es normal. 🛑\"",
   "campaign_id": "",
   "adset_id": "",
   "ad_id": "",
   "gasto_7d": 4540,
   "resultados_7d": 185,
   "costo_resultado": 25,
   "tipo_resultado": "lead",
   "frecuencia": 1.74,
   "pct_nuevos": null,
   "diagnostico": "RINDE BIEN",
   "accion_sugerida": "ESCALAR — subir presupuesto",
   "detalle": "Frecuencia baja (1.74x) + costo/resultado mejor que su cuenta + volumen decente.",
   "nivel_accion": "AD SET",
   "formato_actual": "OTRO",
   "formato_sugerido": null
  },
  {
   "clinica": "Gerontologia",
   "grupo": "sede",
   "campana": "",
   "adset": "BALBUENA",
   "anuncio": "VID _  Gym para personas mayores OMAR _ 08 SEP",
   "campaign_id": "",
   "adset_id": "",
   "ad_id": "",
   "gasto_7d": 3594,
   "resultados_7d": 606,
   "costo_resultado": 6,
   "tipo_resultado": "lead",
   "frecuencia": 1.99,
   "pct_nuevos": null,
   "diagnostico": "RINDE BIEN",
   "accion_sugerida": "ESCALAR — subir presupuesto",
   "detalle": "Frecuencia baja (1.99x) + costo/resultado mejor que su cuenta + volumen decente.",
   "nivel_accion": "AD SET",
   "formato_actual": "VIDEO",
   "formato_sugerido": null
  },
  {
   "clinica": "Laura (sedes)",
   "grupo": "sede",
   "campana": "",
   "adset": "ESPALDA",
   "anuncio": "VID _ CIATICA PADECIMIENTO _ SEP _ OCT",
   "campaign_id": "",
   "adset_id": "",
   "ad_id": "",
   "gasto_7d": 3518,
   "resultados_7d": 248,
   "costo_resultado": 14,
   "tipo_resultado": "lead",
   "frecuencia": 1.44,
   "pct_nuevos": null,
   "diagnostico": "RINDE BIEN",
   "accion_sugerida": "ESCALAR — subir presupuesto",
   "detalle": "Frecuencia baja (1.44x) + costo/resultado mejor que su cuenta + volumen decente.",
   "nivel_accion": "AD SET",
   "formato_actual": "VIDEO",
   "formato_sugerido": null
  },
  {
   "clinica": "Queretaro",
   "grupo": "franquicia",
   "campana": "",
   "adset": "HOMBRO",
   "anuncio": "VID - HOMBRO IRVIN",
   "campaign_id": "",
   "adset_id": "",
   "ad_id": "",
   "gasto_7d": 3232,
   "resultados_7d": 196,
   "costo_resultado": 16,
   "tipo_resultado": "lead",
   "frecuencia": 1.45,
   "pct_nuevos": null,
   "diagnostico": "RINDE BIEN",
   "accion_sugerida": "ESCALAR — subir presupuesto",
   "detalle": "Frecuencia baja (1.45x) + costo/resultado mejor que su cuenta + volumen decente.",
   "nivel_accion": "AD SET",
   "formato_actual": "VIDEO",
   "formato_sugerido": null
  },
  {
   "clinica": "Gerontologia",
   "grupo": "sede",
   "campana": "",
   "adset": "Imagen Gerontologia -  BALBUENA",
   "anuncio": "BALBUENA SABADO",
   "campaign_id": "",
   "adset_id": "",
   "ad_id": "",
   "gasto_7d": 2896,
   "resultados_7d": 480,
   "costo_resultado": 6,
   "tipo_resultado": "lead",
   "frecuencia": 1.69,
   "pct_nuevos": null,
   "diagnostico": "RINDE BIEN",
   "accion_sugerida": "ESCALAR — subir presupuesto",
   "detalle": "Frecuencia baja (1.69x) + costo/resultado mejor que su cuenta + volumen decente.",
   "nivel_accion": "AD SET",
   "formato_actual": "OTRO",
   "formato_sugerido": null
  },
  {
   "clinica": "Promo/Compl.",
   "grupo": "sede",
   "campana": "",
   "adset": "ORGANICO PAUTA",
   "anuncio": "Neuropatia",
   "campaign_id": "",
   "adset_id": "",
   "ad_id": "",
   "gasto_7d": 2388,
   "resultados_7d": 167,
   "costo_resultado": 14,
   "tipo_resultado": "lead",
   "frecuencia": 1.44,
   "pct_nuevos": null,
   "diagnostico": "RINDE BIEN",
   "accion_sugerida": "ESCALAR — subir presupuesto",
   "detalle": "Frecuencia baja (1.44x) + costo/resultado mejor que su cuenta + volumen decente.",
   "nivel_accion": "AD SET",
   "formato_actual": "OTRO",
   "formato_sugerido": null
  },
  {
   "clinica": "Laura (sedes)",
   "grupo": "sede",
   "campana": "",
   "adset": "ESPALDA",
   "anuncio": "VID  _ CERVICALGIA _ SEP",
   "campaign_id": "",
   "adset_id": "",
   "ad_id": "",
   "gasto_7d": 2281,
   "resultados_7d": 174,
   "costo_resultado": 13,
   "tipo_resultado": "lead",
   "frecuencia": 1.35,
   "pct_nuevos": null,
   "diagnostico": "RINDE BIEN",
   "accion_sugerida": "ESCALAR — subir presupuesto",
   "detalle": "Frecuencia baja (1.35x) + costo/resultado mejor que su cuenta + volumen decente.",
   "nivel_accion": "AD SET",
   "formato_actual": "VIDEO",
   "formato_sugerido": null
  },
  {
   "clinica": "Queretaro",
   "grupo": "franquicia",
   "campana": "",
   "adset": "NEUROPATIA",
   "anuncio": "VID - NEURO MARY",
   "campaign_id": "",
   "adset_id": "",
   "ad_id": "",
   "gasto_7d": 2027,
   "resultados_7d": 111,
   "costo_resultado": 18,
   "tipo_resultado": "lead",
   "frecuencia": 1.95,
   "pct_nuevos": null,
   "diagnostico": "RINDE BIEN",
   "accion_sugerida": "ESCALAR — subir presupuesto",
   "detalle": "Frecuencia baja (1.95x) + costo/resultado mejor que su cuenta + volumen decente.",
   "nivel_accion": "AD SET",
   "formato_actual": "VIDEO",
   "formato_sugerido": null
  },
  {
   "clinica": "Promo/Compl.",
   "grupo": "sede",
   "campana": "",
   "adset": "FUNCIONALES 10",
   "anuncio": "FUNCIONALES 2",
   "campaign_id": "",
   "adset_id": "",
   "ad_id": "",
   "gasto_7d": 1880,
   "resultados_7d": 86,
   "costo_resultado": 22,
   "tipo_resultado": "lead",
   "frecuencia": 1.47,
   "pct_nuevos": null,
   "diagnostico": "RINDE BIEN",
   "accion_sugerida": "ESCALAR — subir presupuesto",
   "detalle": "Frecuencia baja (1.47x) + costo/resultado mejor que su cuenta + volumen decente.",
   "nivel_accion": "AD SET",
   "formato_actual": "OTRO",
   "formato_sugerido": null
  },
  {
   "clinica": "Valle Dorado",
   "grupo": "franquicia",
   "campana": "",
   "adset": "HOMBRO",
   "anuncio": "VID _ PADECIMIENTO _ SEP",
   "campaign_id": "",
   "adset_id": "",
   "ad_id": "",
   "gasto_7d": 1287,
   "resultados_7d": 64,
   "costo_resultado": 20,
   "tipo_resultado": "lead",
   "frecuencia": 1.41,
   "pct_nuevos": null,
   "diagnostico": "RINDE BIEN",
   "accion_sugerida": "ESCALAR — subir presupuesto",
   "detalle": "Frecuencia baja (1.41x) + costo/resultado mejor que su cuenta + volumen decente.",
   "nivel_accion": "AD SET",
   "formato_actual": "VIDEO",
   "formato_sugerido": null
  },
  {
   "clinica": "Laura (sedes)",
   "grupo": "sede",
   "campana": "",
   "adset": "ESPALDA - CHECK",
   "anuncio": "EST _ CIATICA V2 _ 14 MAY",
   "campaign_id": "",
   "adset_id": "",
   "ad_id": "",
   "gasto_7d": 1179,
   "resultados_7d": 46,
   "costo_resultado": 26,
   "tipo_resultado": "lead",
   "frecuencia": 1.47,
   "pct_nuevos": null,
   "diagnostico": "RINDE BIEN",
   "accion_sugerida": "ESCALAR — subir presupuesto",
   "detalle": "Frecuencia baja (1.47x) + costo/resultado mejor que su cuenta + volumen decente.",
   "nivel_accion": "AD SET",
   "formato_actual": "IMAGEN",
   "formato_sugerido": null
  },
  {
   "clinica": "Queretaro",
   "grupo": "franquicia",
   "campana": "",
   "adset": "HOMBRO",
   "anuncio": "VID - HOMBRO DOLOROSO JUN",
   "campaign_id": "",
   "adset_id": "",
   "ad_id": "",
   "gasto_7d": 1141,
   "resultados_7d": 63,
   "costo_resultado": 18,
   "tipo_resultado": "lead",
   "frecuencia": 1.43,
   "pct_nuevos": null,
   "diagnostico": "RINDE BIEN",
   "accion_sugerida": "ESCALAR — subir presupuesto",
   "detalle": "Frecuencia baja (1.43x) + costo/resultado mejor que su cuenta + volumen decente.",
   "nivel_accion": "AD SET",
   "formato_actual": "VIDEO",
   "formato_sugerido": null
  },
  {
   "clinica": "Promo/Compl.",
   "grupo": "sede",
   "campana": "",
   "adset": "ORGANICO PAUTA",
   "anuncio": "VID - ACUPUNTURA JUN",
   "campaign_id": "",
   "adset_id": "",
   "ad_id": "",
   "gasto_7d": 1089,
   "resultados_7d": 53,
   "costo_resultado": 21,
   "tipo_resultado": "lead",
   "frecuencia": 1.39,
   "pct_nuevos": null,
   "diagnostico": "RINDE BIEN",
   "accion_sugerida": "ESCALAR — subir presupuesto",
   "detalle": "Frecuencia baja (1.39x) + costo/resultado mejor que su cuenta + volumen decente.",
   "nivel_accion": "AD SET",
   "formato_actual": "VIDEO",
   "formato_sugerido": null
  },
  {
   "clinica": "Gerontologia",
   "grupo": "sede",
   "campana": "",
   "adset": "Imagen Gerontologia - NEZA",
   "anuncio": "NEZA DOMINGOS",
   "campaign_id": "",
   "adset_id": "",
   "ad_id": "",
   "gasto_7d": 632,
   "resultados_7d": 116,
   "costo_resultado": 5,
   "tipo_resultado": "lead",
   "frecuencia": 1.74,
   "pct_nuevos": null,
   "diagnostico": "RINDE BIEN",
   "accion_sugerida": "ESCALAR — subir presupuesto",
   "detalle": "Frecuencia baja (1.74x) + costo/resultado mejor que su cuenta + volumen decente.",
   "nivel_accion": "AD SET",
   "formato_actual": "OTRO",
   "formato_sugerido": null
  },
  {
   "clinica": "Gerontologia",
   "grupo": "sede",
   "campana": "",
   "adset": "Coacalco",
   "anuncio": "VID_CONSULTA_GE _ NUEVO - Copia",
   "campaign_id": "",
   "adset_id": "",
   "ad_id": "",
   "gasto_7d": 604,
   "resultados_7d": 34,
   "costo_resultado": 18,
   "tipo_resultado": "lead",
   "frecuencia": 1.46,
   "pct_nuevos": null,
   "diagnostico": "RINDE BIEN",
   "accion_sugerida": "ESCALAR — subir presupuesto",
   "detalle": "Frecuencia baja (1.46x) + costo/resultado mejor que su cuenta + volumen decente.",
   "nivel_accion": "AD SET",
   "formato_actual": "VIDEO",
   "formato_sugerido": null
  },
  {
   "clinica": "La Moderna",
   "grupo": "franquicia",
   "campana": "",
   "adset": "Espalda",
   "anuncio": "VID_ ESPALDA SINTOMAS _SEP",
   "campaign_id": "",
   "adset_id": "",
   "ad_id": "",
   "gasto_7d": 548,
   "resultados_7d": 25,
   "costo_resultado": 22,
   "tipo_resultado": "lead",
   "frecuencia": 1.29,
   "pct_nuevos": null,
   "diagnostico": "RINDE BIEN",
   "accion_sugerida": "ESCALAR — subir presupuesto",
   "detalle": "Frecuencia baja (1.29x) + costo/resultado mejor que su cuenta + volumen decente.",
   "nivel_accion": "AD SET",
   "formato_actual": "VIDEO",
   "formato_sugerido": null
  },
  {
   "clinica": "Laura (sedes)",
   "grupo": "sede",
   "campana": "",
   "adset": "RODILLA",
   "anuncio": "VID _ DESGASTE _ SEP",
   "campaign_id": "",
   "adset_id": "",
   "ad_id": "",
   "gasto_7d": 512,
   "resultados_7d": 19,
   "costo_resultado": 27,
   "tipo_resultado": "lead",
   "frecuencia": 1.53,
   "pct_nuevos": null,
   "diagnostico": "RINDE BIEN",
   "accion_sugerida": "ESCALAR — subir presupuesto",
   "detalle": "Frecuencia baja (1.53x) + costo/resultado mejor que su cuenta + volumen decente.",
   "nivel_accion": "AD SET",
   "formato_actual": "VIDEO",
   "formato_sugerido": null
  },
  {
   "clinica": "Laura (sedes)",
   "grupo": "sede",
   "campana": "",
   "adset": "Quiropractica",
   "anuncio": "VID - QUIRO ALAN 5 JUN",
   "campaign_id": "",
   "adset_id": "",
   "ad_id": "",
   "gasto_7d": 507,
   "resultados_7d": 25,
   "costo_resultado": 20,
   "tipo_resultado": "lead",
   "frecuencia": 1.87,
   "pct_nuevos": null,
   "diagnostico": "RINDE BIEN",
   "accion_sugerida": "ESCALAR — subir presupuesto",
   "detalle": "Frecuencia baja (1.87x) + costo/resultado mejor que su cuenta + volumen decente.",
   "nivel_accion": "AD SET",
   "formato_actual": "VIDEO",
   "formato_sugerido": null
  }
 ],
 "resumen": {
  "n_apagar": 7,
  "n_cambiar_publico": 1,
  "n_contenido_nuevo": 7,
  "n_vigilar": 14,
  "n_escalar": 25,
  "gasto_liberable_estimado_dia": 10569.14
 }
};
