window.FATIGA_DATA = {
 "actualizado": "28/08/2026 00:15",
 "periodo": "2026-08-01 a 2026-08-28",
 "diagnostico": [
  {
   "cuenta": "San Juan del Rio",
   "adset": "Paralisis -  Check",
   "veredicto": "RENOVAR PUBLICO",
   "freq": 2.42,
   "gasto": 1601,
   "leads": 47,
   "cpl": 34,
   "pct_nuevos": 9,
   "cpm1": 38,
   "cpm2": 36
  },
  {
   "cuenta": "San Juan del Rio",
   "adset": "Neuropatia - Check",
   "veredicto": "RENOVAR PUBLICO",
   "freq": 2.4,
   "gasto": 1519,
   "leads": 48,
   "cpl": 32,
   "pct_nuevos": 16,
   "cpm1": 34,
   "cpm2": 33
  },
  {
   "cuenta": "Laura (sedes)",
   "adset": "Espalda",
   "veredicto": "RENOVAR PUBLICO",
   "freq": 2.14,
   "gasto": 2032,
   "leads": 57,
   "cpl": 36,
   "pct_nuevos": 6,
   "cpm1": 22,
   "cpm2": 26
  },
  {
   "cuenta": "Tepeyac",
   "adset": "Espalda",
   "veredicto": "RENOVAR PUBLICO",
   "freq": 2.01,
   "gasto": 2775,
   "leads": 119,
   "cpl": 23,
   "pct_nuevos": 12,
   "cpm1": 57,
   "cpm2": 59
  },
  {
   "cuenta": "Promo/Compl.",
   "adset": "VIDEO COACALCO",
   "veredicto": "PUBLICO CANSANDOSE",
   "freq": 2.1,
   "gasto": 50799,
   "leads": 793,
   "cpl": 64,
   "pct_nuevos": 22,
   "cpm1": 29,
   "cpm2": 43
  },
  {
   "cuenta": "Laura (sedes)",
   "adset": "VIDEO AJUSCO",
   "veredicto": "PUBLICO CANSANDOSE",
   "freq": 1.99,
   "gasto": 21348,
   "leads": 625,
   "cpl": 34,
   "pct_nuevos": 32,
   "cpm1": 40,
   "cpm2": 51
  },
  {
   "cuenta": "Laura (sedes)",
   "adset": "MIX",
   "veredicto": "PUBLICO CANSANDOSE",
   "freq": 1.78,
   "gasto": 1527,
   "leads": 59,
   "cpl": 26,
   "pct_nuevos": 24,
   "cpm1": 23,
   "cpm2": 33
  },
  {
   "cuenta": "Claveria",
   "adset": "RODILLA - CHECK",
   "veredicto": "PUBLICO CANSANDOSE",
   "freq": 1.53,
   "gasto": 2545,
   "leads": 97,
   "cpl": 26,
   "pct_nuevos": 9,
   "cpm1": 55,
   "cpm2": 73
  },
  {
   "cuenta": "Nicolas Romero",
   "adset": "Publicación: \"¡Atención, Nicolás Romero! ¿Buscas terapia de...\"",
   "veredicto": "CAMBIAR CREATIVO",
   "freq": 3.24,
   "gasto": 24338,
   "leads": 665,
   "cpl": 37,
   "pct_nuevos": 37,
   "cpm1": 23,
   "cpm2": 28
  },
  {
   "cuenta": "Promo/Compl.",
   "adset": "Publicación: \"¿Vives o eres de Mixquiahuala y el dolor de...\"",
   "veredicto": "CAMBIAR CREATIVO",
   "freq": 3.13,
   "gasto": 36483,
   "leads": 545,
   "cpl": 67,
   "pct_nuevos": 35,
   "cpm1": 27,
   "cpm2": 29
  },
  {
   "cuenta": "Pachuca",
   "adset": "NEUROPATÍA",
   "veredicto": "CAMBIAR CREATIVO",
   "freq": 2.99,
   "gasto": 3404,
   "leads": 101,
   "cpl": 34,
   "pct_nuevos": 21,
   "cpm1": 36,
   "cpm2": 40
  },
  {
   "cuenta": "San Juan del Rio",
   "adset": "Publicación: \"Atención zona San Juan del Río. 📍\"",
   "veredicto": "CAMBIAR CREATIVO",
   "freq": 2.88,
   "gasto": 12518,
   "leads": 424,
   "cpl": 30,
   "pct_nuevos": 102,
   "cpm1": 26,
   "cpm2": 29
  },
  {
   "cuenta": "Ajusco",
   "adset": "NEU",
   "veredicto": "CAMBIAR CREATIVO",
   "freq": 2.7,
   "gasto": 3855,
   "leads": 69,
   "cpl": 56,
   "pct_nuevos": 91,
   "cpm1": 50,
   "cpm2": 54
  },
  {
   "cuenta": "Promo/Compl.",
   "adset": "Publicación: \"📍 ¿Vives en Milpa Alta y el dolor de rodilla ya...\"",
   "veredicto": "CAMBIAR CREATIVO",
   "freq": 2.68,
   "gasto": 11326,
   "leads": 592,
   "cpl": 19,
   "pct_nuevos": 828,
   "cpm1": 20,
   "cpm2": 17
  },
  {
   "cuenta": "Promo/Compl.",
   "adset": "Publicación: \"Si eres de Plaza Neza, 📍\"",
   "veredicto": "CAMBIAR CREATIVO",
   "freq": 2.6,
   "gasto": 12925,
   "leads": 516,
   "cpl": 25,
   "pct_nuevos": 128,
   "cpm1": 28,
   "cpm2": 27
  },
  {
   "cuenta": "Laura (sedes)",
   "adset": "Neuropatia",
   "veredicto": "CAMBIAR CREATIVO",
   "freq": 2.54,
   "gasto": 2122,
   "leads": 71,
   "cpl": 30,
   "pct_nuevos": 41,
   "cpm1": 26,
   "cpm2": 29
  },
  {
   "cuenta": "Ajusco",
   "adset": "HOM",
   "veredicto": "VIGILAR",
   "freq": 2.49,
   "gasto": 1838,
   "leads": 23,
   "cpl": 80,
   "pct_nuevos": 35,
   "cpm1": 56,
   "cpm2": 62
  },
  {
   "cuenta": "Gerontologia",
   "adset": "GERO",
   "veredicto": "VIGILAR",
   "freq": 2.45,
   "gasto": 13072,
   "leads": 250,
   "cpl": 52,
   "pct_nuevos": 63,
   "cpm1": 102,
   "cpm2": 83
  },
  {
   "cuenta": "San Juan del Rio",
   "adset": "Rodilla -  Check",
   "veredicto": "VIGILAR",
   "freq": 2.42,
   "gasto": 522,
   "leads": 13,
   "cpl": 40,
   "pct_nuevos": 37,
   "cpm1": 38,
   "cpm2": 35
  },
  {
   "cuenta": "Ajusco",
   "adset": "ROD",
   "veredicto": "VIGILAR",
   "freq": 2.42,
   "gasto": 5297,
   "leads": 84,
   "cpl": 63,
   "pct_nuevos": 43,
   "cpm1": 47,
   "cpm2": 51
  },
  {
   "cuenta": "Nicolas Romero",
   "adset": "RODILLA",
   "veredicto": "VIGILAR",
   "freq": 2.38,
   "gasto": 4832,
   "leads": 296,
   "cpl": 16,
   "pct_nuevos": 38,
   "cpm1": 16,
   "cpm2": 18
  },
  {
   "cuenta": "Promo/Compl.",
   "adset": "Publicación: \"¿Vives con dolor en Ecatepec? 📍\"",
   "veredicto": "VIGILAR",
   "freq": 2.34,
   "gasto": 45383,
   "leads": 1203,
   "cpl": 38,
   "pct_nuevos": 57,
   "cpm1": 35,
   "cpm2": 37
  },
  {
   "cuenta": "La Moderna",
   "adset": "Publicación: \"En Equilibrio Total La Moderna (Iztacalco),...\"",
   "veredicto": "VIGILAR",
   "freq": 2.34,
   "gasto": 7094,
   "leads": 204,
   "cpl": 35,
   "pct_nuevos": 556,
   "cpm1": 44,
   "cpm2": 43
  },
  {
   "cuenta": "Xochimilco",
   "adset": "Publicación: \"¡Atención Zona Sur! ¿Ese dolor de espalda...\"",
   "veredicto": "VIGILAR",
   "freq": 2.33,
   "gasto": 29996,
   "leads": 1102,
   "cpl": 27,
   "pct_nuevos": 36,
   "cpm1": 28,
   "cpm2": 37
  },
  {
   "cuenta": "Gerontologia",
   "adset": "Imagen Gerontologia -  COACALCO",
   "veredicto": "VIGILAR",
   "freq": 2.32,
   "gasto": 2062,
   "leads": 424,
   "cpl": 5,
   "pct_nuevos": 51,
   "cpm1": 38,
   "cpm2": 39
  },
  {
   "cuenta": "Pachuca",
   "adset": "Conjunto de anuncios Campaña de mensajes personalizada 8/8/2026",
   "veredicto": "VIGILAR",
   "freq": 2.32,
   "gasto": 10600,
   "leads": 694,
   "cpl": 15,
   "pct_nuevos": 135,
   "cpm1": 28,
   "cpm2": 32
  },
  {
   "cuenta": "Nicolas Romero",
   "adset": "HOMBRO",
   "veredicto": "VIGILAR",
   "freq": 2.32,
   "gasto": 5950,
   "leads": 475,
   "cpl": 13,
   "pct_nuevos": 42,
   "cpm1": 15,
   "cpm2": 18
  },
  {
   "cuenta": "Laura (sedes)",
   "adset": "Publicación: \"¿Vives en la zona de Tláhuac y el dolor ya forma...\"",
   "veredicto": "VIGILAR",
   "freq": 2.3,
   "gasto": 42711,
   "leads": 952,
   "cpl": 45,
   "pct_nuevos": 34,
   "cpm1": 31,
   "cpm2": 38
  },
  {
   "cuenta": "Promo/Compl.",
   "adset": "Publicación: \"Recupera tu bienestar sin salir de Neza. 🏃‍♂️✨\"",
   "veredicto": "VIGILAR",
   "freq": 2.29,
   "gasto": 63091,
   "leads": 1477,
   "cpl": 43,
   "pct_nuevos": 47,
   "cpm1": 21,
   "cpm2": 27
  },
  {
   "cuenta": "Pachuca",
   "adset": "RODILLA",
   "veredicto": "VIGILAR",
   "freq": 2.29,
   "gasto": 6188,
   "leads": 187,
   "cpl": 33,
   "pct_nuevos": 77,
   "cpm1": 33,
   "cpm2": 30
  },
  {
   "cuenta": "Gerontologia",
   "adset": "Publicación: \"Más movimiento, más independencia y más momentos...\"",
   "veredicto": "VIGILAR",
   "freq": 2.25,
   "gasto": 8015,
   "leads": 851,
   "cpl": 9,
   "pct_nuevos": 71,
   "cpm1": 74,
   "cpm2": 61
  },
  {
   "cuenta": "Cuautla",
   "adset": "Rodilla",
   "veredicto": "VIGILAR",
   "freq": 2.24,
   "gasto": 761,
   "leads": 40,
   "cpl": 19,
   "pct_nuevos": 90,
   "cpm1": 28,
   "cpm2": 25
  },
  {
   "cuenta": "Laura (sedes)",
   "adset": "Rodilla",
   "veredicto": "VIGILAR",
   "freq": 2.2,
   "gasto": 1139,
   "leads": 55,
   "cpl": 21,
   "pct_nuevos": 18,
   "cpm1": 20,
   "cpm2": 26
  }
 ],
 "exitosos": [
  {
   "cuenta": "Gerontologia",
   "ad": "NEZA DOMINGOS",
   "adset": "Imagen Gerontologia - NEZA",
   "freq": 1.96,
   "gasto": 909,
   "leads": 208,
   "cpl": 4
  },
  {
   "cuenta": "Laura (sedes)",
   "ad": "EST-RODILLA-6-MAY",
   "adset": "RODILLA",
   "freq": 1.74,
   "gasto": 511,
   "leads": 46,
   "cpl": 11
  },
  {
   "cuenta": "Laura (sedes)",
   "ad": "VID-NEUROPATIA.SEP",
   "adset": "NEUROPATIA",
   "freq": 1.76,
   "gasto": 4540,
   "leads": 357,
   "cpl": 13
  },
  {
   "cuenta": "Laura (sedes)",
   "ad": "VID-RODILLA2 6-MAY",
   "adset": "RODILLA CHECK",
   "freq": 1.3,
   "gasto": 1095,
   "leads": 59,
   "cpl": 19
  },
  {
   "cuenta": "Laura (sedes)",
   "ad": "VID - IRVIN EXITOSO",
   "adset": "HOMBRO CHECK",
   "freq": 1.78,
   "gasto": 6461,
   "leads": 319,
   "cpl": 20
  },
  {
   "cuenta": "Tepeyac",
   "ad": "VID - NEUROPATIA DIABETICA V2 JUN",
   "adset": "Neuropatia",
   "freq": 1.71,
   "gasto": 898,
   "leads": 44,
   "cpl": 20
  },
  {
   "cuenta": "Cuautitlan",
   "ad": "Publicación: \"Si eres de la zona Cuautitlán Izcalli, 📍\"",
   "adset": "Publicación: \"Si eres de la zona Cuautitlán Izcalli, 📍\"",
   "freq": 1.99,
   "gasto": 15975,
   "leads": 803,
   "cpl": 20
  },
  {
   "cuenta": "Cuautitlan",
   "ad": "EST _ CIATICA V2 _ 14 MAY -",
   "adset": "Directo",
   "freq": 1.31,
   "gasto": 849,
   "leads": 41,
   "cpl": 21
  },
  {
   "cuenta": "Cuautitlan",
   "ad": "VID _ NEUROPATIA  01 ABRIL - Copia",
   "adset": "Directo",
   "freq": 1.4,
   "gasto": 1359,
   "leads": 64,
   "cpl": 21
  },
  {
   "cuenta": "Satelite",
   "ad": "VID-HOMBRODOLOROSO - Copia",
   "adset": "HOMBRO - CHECK",
   "freq": 1.3,
   "gasto": 1870,
   "leads": 85,
   "cpl": 22
  },
  {
   "cuenta": "Tepeyac",
   "ad": "VID - ESTUDIO DE COLUMNA JUL",
   "adset": "Espalda",
   "freq": 1.83,
   "gasto": 2238,
   "leads": 100,
   "cpl": 22
  },
  {
   "cuenta": "Tepeyac",
   "ad": "Publicación: \"📍 ¡Atención Tepeyac y alrededores! ¿El dolor te...\"",
   "adset": "Publicación: \"📍 ¡Atención Tepeyac y alrededores! ¿El dolor te...\"",
   "freq": 1.92,
   "gasto": 7938,
   "leads": 365,
   "cpl": 22
  },
  {
   "cuenta": "Cuautla",
   "ad": "VID - ESPALDA GABO V1 JUN",
   "adset": "Espalda",
   "freq": 1.64,
   "gasto": 614,
   "leads": 28,
   "cpl": 22
  },
  {
   "cuenta": "Laura (sedes)",
   "ad": "VID-NEUROPATIA.SEP",
   "adset": "NEUROPATIA",
   "freq": 1.74,
   "gasto": 2857,
   "leads": 122,
   "cpl": 23
  },
  {
   "cuenta": "Valle Dorado",
   "ad": "Publicación: \"Si eres de Valle Dorado, 📍\"",
   "adset": "Publicación: \"Si eres de Valle Dorado, 📍\"",
   "freq": 1.74,
   "gasto": 9596,
   "leads": 415,
   "cpl": 23
  },
  {
   "cuenta": "Queretaro",
   "ad": "Publicación: \"Trata tu neuropatía de forma segura y con...\"",
   "adset": "Publicación: \"Trata tu neuropatía de forma segura y con...\"",
   "freq": 1.78,
   "gasto": 10271,
   "leads": 450,
   "cpl": 23
  },
  {
   "cuenta": "Tepeyac",
   "ad": "EST - ESPOLON V3 - JUL",
   "adset": "MIX",
   "freq": 1.82,
   "gasto": 2494,
   "leads": 107,
   "cpl": 23
  },
  {
   "cuenta": "La Moderna",
   "ad": "VID_NEU_JUL",
   "adset": "Neuropatia",
   "freq": 1.94,
   "gasto": 2710,
   "leads": 120,
   "cpl": 23
  },
  {
   "cuenta": "Laura (sedes)",
   "ad": "VID - IRVIN EXITOSO",
   "adset": "HOMBRO",
   "freq": 1.46,
   "gasto": 2773,
   "leads": 116,
   "cpl": 24
  },
  {
   "cuenta": "Cuautitlan",
   "ad": "VID _ VARICES _ 01 ABRIL - Copia",
   "adset": "Directo",
   "freq": 1.42,
   "gasto": 726,
   "leads": 30,
   "cpl": 24
  },
  {
   "cuenta": "Laura (sedes)",
   "ad": "VID-HOMBRO",
   "adset": "HOMBRO",
   "freq": 1.33,
   "gasto": 1140,
   "leads": 46,
   "cpl": 25
  },
  {
   "cuenta": "Laura (sedes)",
   "ad": "VID - ANSIEDAD V1 JUL",
   "adset": "MIX",
   "freq": 1.76,
   "gasto": 681,
   "leads": 27,
   "cpl": 25
  },
  {
   "cuenta": "Laura (sedes)",
   "ad": "VID_TOB_FUNDACION",
   "adset": "Servicios / Testimonios",
   "freq": 1.93,
   "gasto": 990,
   "leads": 39,
   "cpl": 25
  },
  {
   "cuenta": "Laura (sedes)",
   "ad": "VID-NEURO-6-MAY",
   "adset": "NEUROPATIA",
   "freq": 1.76,
   "gasto": 656,
   "leads": 26,
   "cpl": 25
  },
  {
   "cuenta": "Claveria",
   "ad": "EST - NEUROPATIA MANO",
   "adset": "NEUROPATIA - CHECK",
   "freq": 1.65,
   "gasto": 2512,
   "leads": 101,
   "cpl": 25
  }
 ],
 "sin_leads": []
};
