window.OPTIMIZACION_DATA = {
 "actualizado": "07/10/2026 10:09",
 "periodo": "2026-09-30 a 2026-10-06 (7 días) + fatiga mes en curso (2026-10-01 a 2026-10-07)",
 "items": [
  {
   "clinica": "Laura (sedes)",
   "grupo": "sede",
   "campana": "",
   "adset": "Rodilla",
   "anuncio": "",
   "campaign_id": "",
   "adset_id": "",
   "ad_id": "",
   "gasto_7d": 2104,
   "resultados_7d": 51,
   "costo_resultado": 41,
   "tipo_resultado": "lead",
   "frecuencia": 2.01,
   "pct_nuevos": 20,
   "diagnostico": "PÚBLICO QUEMADO",
   "accion_sugerida": "CAMBIAR PÚBLICO",
   "detalle": "Fatiga por frecuencia (2.01x), periodo mes en curso (2026-10-01 a 2026-10-07).",
   "nivel_accion": "AD SET",
   "formato_actual": "OTRO",
   "formato_sugerido": null
  },
  {
   "clinica": "San Juan del Rio",
   "grupo": "franquicia",
   "campana": "Publicación: \"Atención zona San Juan del Río. 📍\"",
   "adset": "Publicación: \"Atención zona San Juan del Río. 📍\"",
   "anuncio": "Publicación: \"Atención zona San Juan del Río. 📍\"",
   "campaign_id": "120252782182510754",
   "adset_id": "120252782182650754",
   "ad_id": "120252782183310754",
   "gasto_7d": 1856.55,
   "resultados_7d": 22,
   "costo_resultado": 84.39,
   "tipo_resultado": "lead",
   "frecuencia": 1.65,
   "pct_nuevos": null,
   "diagnostico": "CPL/CPR ALTO (targeting o creativo débil, no es fatiga)",
   "accion_sugerida": "APAGAR o BAJAR PRESUPUESTO",
   "detalle": "Costo por resultado 1.9x el promedio de San Juan del Rio ($45) en los últimos 7 días, con frecuencia baja (1.65x) — no es fatiga, el problema es targeting/creativo desde el inicio.",
   "nivel_accion": "CAMPAÑA (CBO, reasigna si solo pausas 1 anuncio)",
   "formato_actual": "OTRO",
   "formato_sugerido": null
  },
  {
   "clinica": "Gerontologia",
   "grupo": "sede",
   "campana": "Evento 18 oct - Alexa",
   "adset": "Evento 18 oct",
   "anuncio": "EST - EQUILIBRIO ROSA",
   "campaign_id": "120253055286840730",
   "adset_id": "120253055286860730",
   "ad_id": "120253055286850730",
   "gasto_7d": 1280.81,
   "resultados_7d": 26,
   "costo_resultado": 49.26,
   "tipo_resultado": "lead",
   "frecuencia": 1.49,
   "pct_nuevos": null,
   "diagnostico": "CPL/CPR ALTO (targeting o creativo débil, no es fatiga)",
   "accion_sugerida": "APAGAR o BAJAR PRESUPUESTO",
   "detalle": "Costo por resultado 1.9x el promedio de Gerontologia ($26) en los últimos 7 días, con frecuencia baja (1.49x) — no es fatiga, el problema es targeting/creativo desde el inicio.",
   "nivel_accion": "CAMPAÑA (CBO, reasigna si solo pausas 1 anuncio)",
   "formato_actual": "IMAGEN",
   "formato_sugerido": null
  },
  {
   "clinica": "Queretaro",
   "grupo": "franquicia",
   "campana": "Publicación: \"¿Dolor de espalda, hombro o rodilla? 😣\"",
   "adset": "Publicación: \"¿Dolor de espalda, hombro o rodilla? 😣\"",
   "anuncio": "Publicación: \"¿Dolor de espalda, hombro o rodilla? 😣\"",
   "campaign_id": "52597549831525",
   "adset_id": "52597549834325",
   "ad_id": "52597549845525",
   "gasto_7d": 1119.51,
   "resultados_7d": 29,
   "costo_resultado": 38.6,
   "tipo_resultado": "lead",
   "frecuencia": 1.56,
   "pct_nuevos": null,
   "diagnostico": "CPL/CPR ALTO (targeting o creativo débil, no es fatiga)",
   "accion_sugerida": "APAGAR o BAJAR PRESUPUESTO",
   "detalle": "Costo por resultado 1.8x el promedio de Queretaro ($21) en los últimos 7 días, con frecuencia baja (1.56x) — no es fatiga, el problema es targeting/creativo desde el inicio.",
   "nivel_accion": "CAMPAÑA (CBO, reasigna si solo pausas 1 anuncio)",
   "formato_actual": "OTRO",
   "formato_sugerido": null
  },
  {
   "clinica": "Pachuca",
   "grupo": "franquicia",
   "campana": "PACHUCA RECUPERADA V2",
   "adset": "ESPALDA",
   "anuncio": "VID - Estudio_Completo_Columna",
   "campaign_id": "120238913272890018",
   "adset_id": "120238913272900018",
   "ad_id": "120246104102340018",
   "gasto_7d": 1083.92,
   "resultados_7d": 16,
   "costo_resultado": 67.75,
   "tipo_resultado": "lead",
   "frecuencia": 1.91,
   "pct_nuevos": null,
   "diagnostico": "CPL/CPR ALTO (targeting o creativo débil, no es fatiga)",
   "accion_sugerida": "APAGAR o BAJAR PRESUPUESTO",
   "detalle": "Costo por resultado 1.9x el promedio de Pachuca ($36) en los últimos 7 días, con frecuencia baja (1.91x) — no es fatiga, el problema es targeting/creativo desde el inicio.",
   "nivel_accion": "CAMPAÑA (CBO, reasigna si solo pausas 1 anuncio)",
   "formato_actual": "VIDEO",
   "formato_sugerido": null
  },
  {
   "clinica": "Gerontologia",
   "grupo": "sede",
   "campana": "Evento 18 oct - Alexa",
   "adset": "Evento 18 oct",
   "anuncio": "VID - EQUILIBRIO ROSA",
   "campaign_id": "120253055286840730",
   "adset_id": "120253055286860730",
   "ad_id": "120253055292950730",
   "gasto_7d": 911.9,
   "resultados_7d": 18,
   "costo_resultado": 50.66,
   "tipo_resultado": "lead",
   "frecuencia": 1.85,
   "pct_nuevos": null,
   "diagnostico": "CPL/CPR ALTO (targeting o creativo débil, no es fatiga)",
   "accion_sugerida": "APAGAR o BAJAR PRESUPUESTO",
   "detalle": "Costo por resultado 2.0x el promedio de Gerontologia ($26) en los últimos 7 días, con frecuencia baja (1.85x) — no es fatiga, el problema es targeting/creativo desde el inicio.",
   "nivel_accion": "CAMPAÑA (CBO, reasigna si solo pausas 1 anuncio)",
   "formato_actual": "VIDEO",
   "formato_sugerido": null
  },
  {
   "clinica": "Promo/Compl.",
   "grupo": "sede",
   "campana": "",
   "adset": "Publicación: \"En Equilibrio Total seguimos creciendo y buscamos...\"",
   "anuncio": "",
   "campaign_id": "",
   "adset_id": "",
   "ad_id": "",
   "gasto_7d": 2202,
   "resultados_7d": 55,
   "costo_resultado": 40,
   "tipo_resultado": "lead",
   "frecuencia": 2.35,
   "pct_nuevos": 54,
   "diagnostico": "FRECUENCIA SUBIENDO",
   "accion_sugerida": "VIGILAR — sin acción todavía",
   "detalle": "Fatiga por frecuencia (2.35x), periodo mes en curso (2026-10-01 a 2026-10-07).",
   "nivel_accion": "AD SET",
   "formato_actual": "OTRO",
   "formato_sugerido": null
  },
  {
   "clinica": "Laura (sedes)",
   "grupo": "sede",
   "campana": "",
   "adset": "Neuropatia",
   "anuncio": "",
   "campaign_id": "",
   "adset_id": "",
   "ad_id": "",
   "gasto_7d": 1856,
   "resultados_7d": 77,
   "costo_resultado": 24,
   "tipo_resultado": "lead",
   "frecuencia": 2.35,
   "pct_nuevos": 64,
   "diagnostico": "FRECUENCIA SUBIENDO",
   "accion_sugerida": "VIGILAR — sin acción todavía",
   "detalle": "Fatiga por frecuencia (2.35x), periodo mes en curso (2026-10-01 a 2026-10-07).",
   "nivel_accion": "AD SET",
   "formato_actual": "OTRO",
   "formato_sugerido": null
  },
  {
   "clinica": "San Juan del Rio",
   "grupo": "franquicia",
   "campana": "",
   "adset": "Neuropatia - Check",
   "anuncio": "",
   "campaign_id": "",
   "adset_id": "",
   "ad_id": "",
   "gasto_7d": 1231,
   "resultados_7d": 53,
   "costo_resultado": 23,
   "tipo_resultado": "lead",
   "frecuencia": 2.21,
   "pct_nuevos": 164,
   "diagnostico": "FRECUENCIA SUBIENDO",
   "accion_sugerida": "VIGILAR — sin acción todavía",
   "detalle": "Fatiga por frecuencia (2.21x), periodo mes en curso (2026-10-01 a 2026-10-07).",
   "nivel_accion": "AD SET",
   "formato_actual": "OTRO",
   "formato_sugerido": null
  },
  {
   "clinica": "Promo/Compl.",
   "grupo": "sede",
   "campana": "",
   "adset": "PROMOCIONES CDMX",
   "anuncio": "FEED",
   "campaign_id": "",
   "adset_id": "",
   "ad_id": "",
   "gasto_7d": 8204,
   "resultados_7d": 296,
   "costo_resultado": 28,
   "tipo_resultado": "lead",
   "frecuencia": 1.26,
   "pct_nuevos": null,
   "diagnostico": "RINDE BIEN",
   "accion_sugerida": "ESCALAR — subir presupuesto",
   "detalle": "Frecuencia baja (1.26x) + costo/resultado mejor que su cuenta + volumen decente.",
   "nivel_accion": "AD SET",
   "formato_actual": "OTRO",
   "formato_sugerido": null
  },
  {
   "clinica": "Pachuca",
   "grupo": "franquicia",
   "campana": "",
   "adset": "Conjunto de anuncios Campaña de mensajes personalizada 8/8/2026",
   "anuncio": "Anuncio Campaña de mensajes personalizada 8/8/2026",
   "campaign_id": "",
   "adset_id": "",
   "ad_id": "",
   "gasto_7d": 7442,
   "resultados_7d": 262,
   "costo_resultado": 28,
   "tipo_resultado": "lead",
   "frecuencia": 1.52,
   "pct_nuevos": null,
   "diagnostico": "RINDE BIEN",
   "accion_sugerida": "ESCALAR — subir presupuesto",
   "detalle": "Frecuencia baja (1.52x) + costo/resultado mejor que su cuenta + volumen decente.",
   "nivel_accion": "AD SET",
   "formato_actual": "OTRO",
   "formato_sugerido": null
  },
  {
   "clinica": "Laura (sedes)",
   "grupo": "sede",
   "campana": "",
   "adset": "ESPALDA",
   "anuncio": "VID _ CIATICA PADECIMIENTO _ SEP _ OCT",
   "campaign_id": "",
   "adset_id": "",
   "ad_id": "",
   "gasto_7d": 7280,
   "resultados_7d": 237,
   "costo_resultado": 31,
   "tipo_resultado": "lead",
   "frecuencia": 1.5,
   "pct_nuevos": null,
   "diagnostico": "RINDE BIEN",
   "accion_sugerida": "ESCALAR — subir presupuesto",
   "detalle": "Frecuencia baja (1.5x) + costo/resultado mejor que su cuenta + volumen decente.",
   "nivel_accion": "AD SET",
   "formato_actual": "VIDEO",
   "formato_sugerido": null
  },
  {
   "clinica": "Xochimilco",
   "grupo": "franquicia",
   "campana": "",
   "adset": "Publicación: \"🌿 En Equilibrio Total Xochimilco llevamos años...\"",
   "anuncio": "Publicación: \"🌿 En Equilibrio Total Xochimilco llevamos años...\"",
   "campaign_id": "",
   "adset_id": "",
   "ad_id": "",
   "gasto_7d": 7192,
   "resultados_7d": 247,
   "costo_resultado": 29,
   "tipo_resultado": "lead",
   "frecuencia": 1.4,
   "pct_nuevos": null,
   "diagnostico": "RINDE BIEN",
   "accion_sugerida": "ESCALAR — subir presupuesto",
   "detalle": "Frecuencia baja (1.4x) + costo/resultado mejor que su cuenta + volumen decente.",
   "nivel_accion": "AD SET",
   "formato_actual": "OTRO",
   "formato_sugerido": null
  },
  {
   "clinica": "Laura (sedes)",
   "grupo": "sede",
   "campana": "",
   "adset": "ESPALDA",
   "anuncio": "VID  _ CERVICALGIA _ SEP",
   "campaign_id": "",
   "adset_id": "",
   "ad_id": "",
   "gasto_7d": 4858,
   "resultados_7d": 158,
   "costo_resultado": 31,
   "tipo_resultado": "lead",
   "frecuencia": 1.39,
   "pct_nuevos": null,
   "diagnostico": "RINDE BIEN",
   "accion_sugerida": "ESCALAR — subir presupuesto",
   "detalle": "Frecuencia baja (1.39x) + costo/resultado mejor que su cuenta + volumen decente.",
   "nivel_accion": "AD SET",
   "formato_actual": "VIDEO",
   "formato_sugerido": null
  },
  {
   "clinica": "Nicolas Romero",
   "grupo": "franquicia",
   "campana": "",
   "adset": "HOMBRO",
   "anuncio": "VID_HOMBNICO_JUL",
   "campaign_id": "",
   "adset_id": "",
   "ad_id": "",
   "gasto_7d": 3065,
   "resultados_7d": 111,
   "costo_resultado": 28,
   "tipo_resultado": "lead",
   "frecuencia": 1.43,
   "pct_nuevos": null,
   "diagnostico": "RINDE BIEN",
   "accion_sugerida": "ESCALAR — subir presupuesto",
   "detalle": "Frecuencia baja (1.43x) + costo/resultado mejor que su cuenta + volumen decente.",
   "nivel_accion": "AD SET",
   "formato_actual": "VIDEO",
   "formato_sugerido": null
  },
  {
   "clinica": "Laura (sedes)",
   "grupo": "sede",
   "campana": "",
   "adset": "Espalda",
   "anuncio": "VID_ CIATICA _ SEP _ OCT - 3 OCT",
   "campaign_id": "",
   "adset_id": "",
   "ad_id": "",
   "gasto_7d": 2082,
   "resultados_7d": 92,
   "costo_resultado": 23,
   "tipo_resultado": "lead",
   "frecuencia": 1.54,
   "pct_nuevos": null,
   "diagnostico": "RINDE BIEN",
   "accion_sugerida": "ESCALAR — subir presupuesto",
   "detalle": "Frecuencia baja (1.54x) + costo/resultado mejor que su cuenta + volumen decente.",
   "nivel_accion": "AD SET",
   "formato_actual": "VIDEO",
   "formato_sugerido": null
  },
  {
   "clinica": "Queretaro",
   "grupo": "franquicia",
   "campana": "",
   "adset": "HOMBRO",
   "anuncio": "VID - HOMBRO IRVIN",
   "campaign_id": "",
   "adset_id": "",
   "ad_id": "",
   "gasto_7d": 1592,
   "resultados_7d": 93,
   "costo_resultado": 17,
   "tipo_resultado": "lead",
   "frecuencia": 1.25,
   "pct_nuevos": null,
   "diagnostico": "RINDE BIEN",
   "accion_sugerida": "ESCALAR — subir presupuesto",
   "detalle": "Frecuencia baja (1.25x) + costo/resultado mejor que su cuenta + volumen decente.",
   "nivel_accion": "AD SET",
   "formato_actual": "VIDEO",
   "formato_sugerido": null
  },
  {
   "clinica": "Valle Dorado",
   "grupo": "franquicia",
   "campana": "",
   "adset": "ESPALDA",
   "anuncio": "VID_QUIRO ESPALDA",
   "campaign_id": "",
   "adset_id": "",
   "ad_id": "",
   "gasto_7d": 1497,
   "resultados_7d": 50,
   "costo_resultado": 30,
   "tipo_resultado": "lead",
   "frecuencia": 1.23,
   "pct_nuevos": null,
   "diagnostico": "RINDE BIEN",
   "accion_sugerida": "ESCALAR — subir presupuesto",
   "detalle": "Frecuencia baja (1.23x) + costo/resultado mejor que su cuenta + volumen decente.",
   "nivel_accion": "AD SET",
   "formato_actual": "VIDEO",
   "formato_sugerido": null
  },
  {
   "clinica": "Gerontologia",
   "grupo": "sede",
   "campana": "",
   "adset": "Coacalco",
   "anuncio": "VID_CONSULTA_GE _ NUEVO - Copia",
   "campaign_id": "",
   "adset_id": "",
   "ad_id": "",
   "gasto_7d": 1496,
   "resultados_7d": 75,
   "costo_resultado": 20,
   "tipo_resultado": "lead",
   "frecuencia": 1.29,
   "pct_nuevos": null,
   "diagnostico": "RINDE BIEN",
   "accion_sugerida": "ESCALAR — subir presupuesto",
   "detalle": "Frecuencia baja (1.29x) + costo/resultado mejor que su cuenta + volumen decente.",
   "nivel_accion": "AD SET",
   "formato_actual": "VIDEO",
   "formato_sugerido": null
  },
  {
   "clinica": "Promo/Compl.",
   "grupo": "sede",
   "campana": "",
   "adset": "Neuropatia",
   "anuncio": "VID - NEURO SINTOMAS - OCT",
   "campaign_id": "",
   "adset_id": "",
   "ad_id": "",
   "gasto_7d": 1456,
   "resultados_7d": 66,
   "costo_resultado": 22,
   "tipo_resultado": "lead",
   "frecuencia": 1.5,
   "pct_nuevos": null,
   "diagnostico": "RINDE BIEN",
   "accion_sugerida": "ESCALAR — subir presupuesto",
   "detalle": "Frecuencia baja (1.5x) + costo/resultado mejor que su cuenta + volumen decente.",
   "nivel_accion": "AD SET",
   "formato_actual": "VIDEO",
   "formato_sugerido": null
  },
  {
   "clinica": "Cuautitlan",
   "grupo": "franquicia",
   "campana": "",
   "adset": "Directo",
   "anuncio": "VID_QUIRO _ 1 ABRIL - Copia 2",
   "campaign_id": "",
   "adset_id": "",
   "ad_id": "",
   "gasto_7d": 1361,
   "resultados_7d": 70,
   "costo_resultado": 19,
   "tipo_resultado": "lead",
   "frecuencia": 1.25,
   "pct_nuevos": null,
   "diagnostico": "RINDE BIEN",
   "accion_sugerida": "ESCALAR — subir presupuesto",
   "detalle": "Frecuencia baja (1.25x) + costo/resultado mejor que su cuenta + volumen decente.",
   "nivel_accion": "AD SET",
   "formato_actual": "VIDEO",
   "formato_sugerido": null
  },
  {
   "clinica": "Queretaro",
   "grupo": "franquicia",
   "campana": "",
   "adset": "Publicación: \"Trata tu neuropatía de forma segura y con...\"",
   "anuncio": "Publicación: \"Trata tu neuropatía de forma segura y con...\"",
   "campaign_id": "",
   "adset_id": "",
   "ad_id": "",
   "gasto_7d": 1297,
   "resultados_7d": 68,
   "costo_resultado": 19,
   "tipo_resultado": "lead",
   "frecuencia": 1.64,
   "pct_nuevos": null,
   "diagnostico": "RINDE BIEN",
   "accion_sugerida": "ESCALAR — subir presupuesto",
   "detalle": "Frecuencia baja (1.64x) + costo/resultado mejor que su cuenta + volumen decente.",
   "nivel_accion": "AD SET",
   "formato_actual": "OTRO",
   "formato_sugerido": null
  },
  {
   "clinica": "Gerontologia",
   "grupo": "sede",
   "campana": "",
   "adset": "Imagen Gerontologia - NEZA",
   "anuncio": "NEZA DOMINGOS",
   "campaign_id": "",
   "adset_id": "",
   "ad_id": "",
   "gasto_7d": 1097,
   "resultados_7d": 213,
   "costo_resultado": 5,
   "tipo_resultado": "lead",
   "frecuencia": 1.5,
   "pct_nuevos": null,
   "diagnostico": "RINDE BIEN",
   "accion_sugerida": "ESCALAR — subir presupuesto",
   "detalle": "Frecuencia baja (1.5x) + costo/resultado mejor que su cuenta + volumen decente.",
   "nivel_accion": "AD SET",
   "formato_actual": "OTRO",
   "formato_sugerido": null
  },
  {
   "clinica": "Cuautla",
   "grupo": "franquicia",
   "campana": "",
   "adset": "Neuropatia",
   "anuncio": "NEUROPATIA MARY",
   "campaign_id": "",
   "adset_id": "",
   "ad_id": "",
   "gasto_7d": 1006,
   "resultados_7d": 34,
   "costo_resultado": 30,
   "tipo_resultado": "lead",
   "frecuencia": 1.65,
   "pct_nuevos": null,
   "diagnostico": "RINDE BIEN",
   "accion_sugerida": "ESCALAR — subir presupuesto",
   "detalle": "Frecuencia baja (1.65x) + costo/resultado mejor que su cuenta + volumen decente.",
   "nivel_accion": "AD SET",
   "formato_actual": "OTRO",
   "formato_sugerido": null
  },
  {
   "clinica": "Cuautitlan",
   "grupo": "franquicia",
   "campana": "",
   "adset": "Directo",
   "anuncio": "VID _ NEUROPATIA  01 ABRIL - Copia",
   "campaign_id": "",
   "adset_id": "",
   "ad_id": "",
   "gasto_7d": 953,
   "resultados_7d": 43,
   "costo_resultado": 22,
   "tipo_resultado": "lead",
   "frecuencia": 1.33,
   "pct_nuevos": null,
   "diagnostico": "RINDE BIEN",
   "accion_sugerida": "ESCALAR — subir presupuesto",
   "detalle": "Frecuencia baja (1.33x) + costo/resultado mejor que su cuenta + volumen decente.",
   "nivel_accion": "AD SET",
   "formato_actual": "VIDEO",
   "formato_sugerido": null
  },
  {
   "clinica": "Queretaro",
   "grupo": "franquicia",
   "campana": "",
   "adset": "NEUROPATIA",
   "anuncio": "VID - NEURO MARY",
   "campaign_id": "",
   "adset_id": "",
   "ad_id": "",
   "gasto_7d": 898,
   "resultados_7d": 48,
   "costo_resultado": 19,
   "tipo_resultado": "lead",
   "frecuencia": 1.55,
   "pct_nuevos": null,
   "diagnostico": "RINDE BIEN",
   "accion_sugerida": "ESCALAR — subir presupuesto",
   "detalle": "Frecuencia baja (1.55x) + costo/resultado mejor que su cuenta + volumen decente.",
   "nivel_accion": "AD SET",
   "formato_actual": "VIDEO",
   "formato_sugerido": null
  },
  {
   "clinica": "Laura (sedes)",
   "grupo": "sede",
   "campana": "",
   "adset": "Neuropatia",
   "anuncio": "VID_ NEUROPATIA DIABETICA _ SEP _ OCT",
   "campaign_id": "",
   "adset_id": "",
   "ad_id": "",
   "gasto_7d": 800,
   "resultados_7d": 41,
   "costo_resultado": 20,
   "tipo_resultado": "lead",
   "frecuencia": 1.79,
   "pct_nuevos": null,
   "diagnostico": "RINDE BIEN",
   "accion_sugerida": "ESCALAR — subir presupuesto",
   "detalle": "Frecuencia baja (1.79x) + costo/resultado mejor que su cuenta + volumen decente.",
   "nivel_accion": "AD SET",
   "formato_actual": "VIDEO",
   "formato_sugerido": null
  },
  {
   "clinica": "Promo/Compl.",
   "grupo": "sede",
   "campana": "",
   "adset": "ORGANICO PAUTA",
   "anuncio": "VID - ACUPUNTURA JUN",
   "campaign_id": "",
   "adset_id": "",
   "ad_id": "",
   "gasto_7d": 713,
   "resultados_7d": 27,
   "costo_resultado": 26,
   "tipo_resultado": "lead",
   "frecuencia": 1.42,
   "pct_nuevos": null,
   "diagnostico": "RINDE BIEN",
   "accion_sugerida": "ESCALAR — subir presupuesto",
   "detalle": "Frecuencia baja (1.42x) + costo/resultado mejor que su cuenta + volumen decente.",
   "nivel_accion": "AD SET",
   "formato_actual": "VIDEO",
   "formato_sugerido": null
  },
  {
   "clinica": "San Juan del Rio",
   "grupo": "franquicia",
   "campana": "",
   "adset": "Neuropatia - Check",
   "anuncio": "VID_ NEUROPATIA DIABETICA _ SEP _ OCT",
   "campaign_id": "",
   "adset_id": "",
   "ad_id": "",
   "gasto_7d": 655,
   "resultados_7d": 33,
   "costo_resultado": 20,
   "tipo_resultado": "lead",
   "frecuencia": 1.69,
   "pct_nuevos": null,
   "diagnostico": "RINDE BIEN",
   "accion_sugerida": "ESCALAR — subir presupuesto",
   "detalle": "Frecuencia baja (1.69x) + costo/resultado mejor que su cuenta + volumen decente.",
   "nivel_accion": "AD SET",
   "formato_actual": "VIDEO",
   "formato_sugerido": null
  },
  {
   "clinica": "Laura (sedes)",
   "grupo": "sede",
   "campana": "",
   "adset": "Tropicalizados",
   "anuncio": "EST - NEURO - OCT - 6 OCT",
   "campaign_id": "",
   "adset_id": "",
   "ad_id": "",
   "gasto_7d": 627,
   "resultados_7d": 25,
   "costo_resultado": 25,
   "tipo_resultado": "lead",
   "frecuencia": 1.34,
   "pct_nuevos": null,
   "diagnostico": "RINDE BIEN",
   "accion_sugerida": "ESCALAR — subir presupuesto",
   "detalle": "Frecuencia baja (1.34x) + costo/resultado mejor que su cuenta + volumen decente.",
   "nivel_accion": "AD SET",
   "formato_actual": "IMAGEN",
   "formato_sugerido": null
  },
  {
   "clinica": "Laura (sedes)",
   "grupo": "sede",
   "campana": "",
   "adset": "RODILLA",
   "anuncio": "VID - RODILLA - OCT",
   "campaign_id": "",
   "adset_id": "",
   "ad_id": "",
   "gasto_7d": 584,
   "resultados_7d": 22,
   "costo_resultado": 27,
   "tipo_resultado": "lead",
   "frecuencia": 1.34,
   "pct_nuevos": null,
   "diagnostico": "RINDE BIEN",
   "accion_sugerida": "ESCALAR — subir presupuesto",
   "detalle": "Frecuencia baja (1.34x) + costo/resultado mejor que su cuenta + volumen decente.",
   "nivel_accion": "AD SET",
   "formato_actual": "VIDEO",
   "formato_sugerido": null
  },
  {
   "clinica": "Gerontologia",
   "grupo": "sede",
   "campana": "",
   "adset": "Imagen Gerontologia -  COACALCO",
   "anuncio": "COACALCO VIERNES",
   "campaign_id": "",
   "adset_id": "",
   "ad_id": "",
   "gasto_7d": 545,
   "resultados_7d": 83,
   "costo_resultado": 7,
   "tipo_resultado": "lead",
   "frecuencia": 1.53,
   "pct_nuevos": null,
   "diagnostico": "RINDE BIEN",
   "accion_sugerida": "ESCALAR — subir presupuesto",
   "detalle": "Frecuencia baja (1.53x) + costo/resultado mejor que su cuenta + volumen decente.",
   "nivel_accion": "AD SET",
   "formato_actual": "OTRO",
   "formato_sugerido": null
  },
  {
   "clinica": "San Juan del Rio",
   "grupo": "franquicia",
   "campana": "",
   "adset": "Rodilla -  Check",
   "anuncio": "VID_ RODILLA GENERAL _ SEP _ OCT",
   "campaign_id": "",
   "adset_id": "",
   "ad_id": "",
   "gasto_7d": 531,
   "resultados_7d": 24,
   "costo_resultado": 22,
   "tipo_resultado": "lead",
   "frecuencia": 1.53,
   "pct_nuevos": null,
   "diagnostico": "RINDE BIEN",
   "accion_sugerida": "ESCALAR — subir presupuesto",
   "detalle": "Frecuencia baja (1.53x) + costo/resultado mejor que su cuenta + volumen decente.",
   "nivel_accion": "AD SET",
   "formato_actual": "VIDEO",
   "formato_sugerido": null
  },
  {
   "clinica": "La Moderna",
   "grupo": "franquicia",
   "campana": "",
   "adset": "Espalda",
   "anuncio": "VID PADECIMIENTO CIATICA _ SEP",
   "campaign_id": "",
   "adset_id": "",
   "ad_id": "",
   "gasto_7d": 525,
   "resultados_7d": 18,
   "costo_resultado": 29,
   "tipo_resultado": "lead",
   "frecuencia": 1.26,
   "pct_nuevos": null,
   "diagnostico": "RINDE BIEN",
   "accion_sugerida": "ESCALAR — subir presupuesto",
   "detalle": "Frecuencia baja (1.26x) + costo/resultado mejor que su cuenta + volumen decente.",
   "nivel_accion": "AD SET",
   "formato_actual": "VIDEO",
   "formato_sugerido": null
  }
 ],
 "resumen": {
  "n_apagar": 0,
  "n_cambiar_publico": 1,
  "n_contenido_nuevo": 0,
  "n_vigilar": 3,
  "n_escalar": 25,
  "gasto_liberable_estimado_dia": 0
 }
};
