window.OPTIMIZACION_DATA = {
 "actualizado": "06/10/2026 05:21",
 "periodo": "2026-09-29 a 2026-10-05 (7 días) + fatiga mes en curso (2026-10-01 a 2026-10-06)",
 "items": [
  {
   "clinica": "Promo/Compl.",
   "grupo": "sede",
   "campana": "Reclutamiento Neza",
   "adset": "Publicación: \"En Equilibrio Total seguimos creciendo y buscamos...\"",
   "anuncio": "Publicación: \"En Equilibrio Total seguimos creciendo y buscamos...\"",
   "campaign_id": "120250439639590739",
   "adset_id": "120250439639980739",
   "ad_id": "120250439641790739",
   "gasto_7d": 2378.62,
   "resultados_7d": 23,
   "costo_resultado": 103.42,
   "tipo_resultado": "lead",
   "frecuencia": 2.29,
   "pct_nuevos": null,
   "diagnostico": "CPL/CPR ALTO (targeting o creativo débil, no es fatiga)",
   "accion_sugerida": "APAGAR o BAJAR PRESUPUESTO",
   "detalle": "Costo por resultado 2.0x el promedio de Promo/Compl. ($52) en los últimos 7 días, con frecuencia baja (2.29x) — no es fatiga, el problema es targeting/creativo desde el inicio.",
   "nivel_accion": "ANUNCIO",
   "formato_actual": "OTRO",
   "formato_sugerido": null
  },
  {
   "clinica": "Gerontologia",
   "grupo": "sede",
   "campana": "Evento 18 oct - Alexa",
   "adset": "Evento 18 oct",
   "anuncio": "VID - EQUILIBRIO ROSA",
   "campaign_id": "120253055286840730",
   "adset_id": "120253055286860730",
   "ad_id": "120253055292950730",
   "gasto_7d": 1138.06,
   "resultados_7d": 18,
   "costo_resultado": 63.23,
   "tipo_resultado": "lead",
   "frecuencia": 2.06,
   "pct_nuevos": null,
   "diagnostico": "CPL/CPR ALTO (targeting o creativo débil, no es fatiga)",
   "accion_sugerida": "APAGAR o BAJAR PRESUPUESTO",
   "detalle": "Costo por resultado 2.4x el promedio de Gerontologia ($26) en los últimos 7 días, con frecuencia baja (2.06x) — no es fatiga, el problema es targeting/creativo desde el inicio.",
   "nivel_accion": "CAMPAÑA (CBO, reasigna si solo pausas 1 anuncio)",
   "formato_actual": "VIDEO",
   "formato_sugerido": null
  },
  {
   "clinica": "Pachuca",
   "grupo": "franquicia",
   "campana": "PACHUCA RECUPERADA V2",
   "adset": "ESPALDA",
   "anuncio": "VID - Estudio_Completo_Columna",
   "campaign_id": "120238913272890018",
   "adset_id": "120238913272900018",
   "ad_id": "120246104102340018",
   "gasto_7d": 976.84,
   "resultados_7d": 12,
   "costo_resultado": 81.4,
   "tipo_resultado": "lead",
   "frecuencia": 1.93,
   "pct_nuevos": null,
   "diagnostico": "CPL/CPR ALTO (targeting o creativo débil, no es fatiga)",
   "accion_sugerida": "APAGAR o BAJAR PRESUPUESTO",
   "detalle": "Costo por resultado 2.0x el promedio de Pachuca ($41) en los últimos 7 días, con frecuencia baja (1.93x) — no es fatiga, el problema es targeting/creativo desde el inicio.",
   "nivel_accion": "CAMPAÑA (CBO, reasigna si solo pausas 1 anuncio)",
   "formato_actual": "VIDEO",
   "formato_sugerido": null
  },
  {
   "clinica": "Gerontologia",
   "grupo": "sede",
   "campana": "Evento 18 oct - Alexa",
   "adset": "Evento 18 oct",
   "anuncio": "EST - EQUILIBRIO ROSA",
   "campaign_id": "120253055286840730",
   "adset_id": "120253055286860730",
   "ad_id": "120253055286850730",
   "gasto_7d": 804.79,
   "resultados_7d": 14,
   "costo_resultado": 57.48,
   "tipo_resultado": "lead",
   "frecuencia": 1.54,
   "pct_nuevos": null,
   "diagnostico": "CPL/CPR ALTO (targeting o creativo débil, no es fatiga)",
   "accion_sugerida": "APAGAR o BAJAR PRESUPUESTO",
   "detalle": "Costo por resultado 2.2x el promedio de Gerontologia ($26) en los últimos 7 días, con frecuencia baja (1.54x) — no es fatiga, el problema es targeting/creativo desde el inicio.",
   "nivel_accion": "CAMPAÑA (CBO, reasigna si solo pausas 1 anuncio)",
   "formato_actual": "IMAGEN",
   "formato_sugerido": null
  },
  {
   "clinica": "Laura (sedes)",
   "grupo": "sede",
   "campana": "BALBUENA - CHECK",
   "adset": "RODILLA CHECK",
   "anuncio": "VID_ RODILLA MES _ SEP _ OCT",
   "campaign_id": "120243382688040571",
   "adset_id": "120244103455360571",
   "ad_id": "120247791933140571",
   "gasto_7d": 573.87,
   "resultados_7d": 6,
   "costo_resultado": 95.64,
   "tipo_resultado": "lead",
   "frecuencia": 1.35,
   "pct_nuevos": null,
   "diagnostico": "CPL/CPR ALTO (targeting o creativo débil, no es fatiga)",
   "accion_sugerida": "APAGAR o BAJAR PRESUPUESTO",
   "detalle": "Costo por resultado 2.1x el promedio de Laura (sedes) ($46) en los últimos 7 días, con frecuencia baja (1.35x) — no es fatiga, el problema es targeting/creativo desde el inicio.",
   "nivel_accion": "CAMPAÑA (CBO, reasigna si solo pausas 1 anuncio)",
   "formato_actual": "VIDEO",
   "formato_sugerido": null
  },
  {
   "clinica": "Laura (sedes)",
   "grupo": "sede",
   "campana": "",
   "adset": "ESPALDA",
   "anuncio": "VID _ CIATICA PADECIMIENTO _ SEP _ OCT",
   "campaign_id": "",
   "adset_id": "",
   "ad_id": "",
   "gasto_7d": 6139,
   "resultados_7d": 198,
   "costo_resultado": 31,
   "tipo_resultado": "lead",
   "frecuencia": 1.45,
   "pct_nuevos": null,
   "diagnostico": "RINDE BIEN",
   "accion_sugerida": "ESCALAR — subir presupuesto",
   "detalle": "Frecuencia baja (1.45x) + costo/resultado mejor que su cuenta + volumen decente.",
   "nivel_accion": "AD SET",
   "formato_actual": "VIDEO",
   "formato_sugerido": null
  },
  {
   "clinica": "Promo/Compl.",
   "grupo": "sede",
   "campana": "",
   "adset": "PROMOCIONES CDMX",
   "anuncio": "FEED",
   "campaign_id": "",
   "adset_id": "",
   "ad_id": "",
   "gasto_7d": 5906,
   "resultados_7d": 226,
   "costo_resultado": 26,
   "tipo_resultado": "lead",
   "frecuencia": 1.26,
   "pct_nuevos": null,
   "diagnostico": "RINDE BIEN",
   "accion_sugerida": "ESCALAR — subir presupuesto",
   "detalle": "Frecuencia baja (1.26x) + costo/resultado mejor que su cuenta + volumen decente.",
   "nivel_accion": "AD SET",
   "formato_actual": "OTRO",
   "formato_sugerido": null
  },
  {
   "clinica": "Pachuca",
   "grupo": "franquicia",
   "campana": "",
   "adset": "Conjunto de anuncios Campaña de mensajes personalizada 8/8/2026",
   "anuncio": "Anuncio Campaña de mensajes personalizada 8/8/2026",
   "campaign_id": "",
   "adset_id": "",
   "ad_id": "",
   "gasto_7d": 5514,
   "resultados_7d": 208,
   "costo_resultado": 27,
   "tipo_resultado": "lead",
   "frecuencia": 1.46,
   "pct_nuevos": null,
   "diagnostico": "RINDE BIEN",
   "accion_sugerida": "ESCALAR — subir presupuesto",
   "detalle": "Frecuencia baja (1.46x) + costo/resultado mejor que su cuenta + volumen decente.",
   "nivel_accion": "AD SET",
   "formato_actual": "OTRO",
   "formato_sugerido": null
  },
  {
   "clinica": "Promo/Compl.",
   "grupo": "sede",
   "campana": "",
   "adset": "Neuropatia",
   "anuncio": "VID - NEURO PADECIMIENTO - OCT",
   "campaign_id": "",
   "adset_id": "",
   "ad_id": "",
   "gasto_7d": 5283,
   "resultados_7d": 167,
   "costo_resultado": 32,
   "tipo_resultado": "lead",
   "frecuencia": 1.69,
   "pct_nuevos": null,
   "diagnostico": "RINDE BIEN",
   "accion_sugerida": "ESCALAR — subir presupuesto",
   "detalle": "Frecuencia baja (1.69x) + costo/resultado mejor que su cuenta + volumen decente.",
   "nivel_accion": "AD SET",
   "formato_actual": "VIDEO",
   "formato_sugerido": null
  },
  {
   "clinica": "Xochimilco",
   "grupo": "franquicia",
   "campana": "",
   "adset": "Publicación: \"🌿 En Equilibrio Total Xochimilco llevamos años...\"",
   "anuncio": "Publicación: \"🌿 En Equilibrio Total Xochimilco llevamos años...\"",
   "campaign_id": "",
   "adset_id": "",
   "ad_id": "",
   "gasto_7d": 5162,
   "resultados_7d": 192,
   "costo_resultado": 27,
   "tipo_resultado": "lead",
   "frecuencia": 1.35,
   "pct_nuevos": null,
   "diagnostico": "RINDE BIEN",
   "accion_sugerida": "ESCALAR — subir presupuesto",
   "detalle": "Frecuencia baja (1.35x) + costo/resultado mejor que su cuenta + volumen decente.",
   "nivel_accion": "AD SET",
   "formato_actual": "OTRO",
   "formato_sugerido": null
  },
  {
   "clinica": "Laura (sedes)",
   "grupo": "sede",
   "campana": "",
   "adset": "ESPALDA",
   "anuncio": "VID  _ CERVICALGIA _ SEP",
   "campaign_id": "",
   "adset_id": "",
   "ad_id": "",
   "gasto_7d": 4007,
   "resultados_7d": 126,
   "costo_resultado": 32,
   "tipo_resultado": "lead",
   "frecuencia": 1.33,
   "pct_nuevos": null,
   "diagnostico": "RINDE BIEN",
   "accion_sugerida": "ESCALAR — subir presupuesto",
   "detalle": "Frecuencia baja (1.33x) + costo/resultado mejor que su cuenta + volumen decente.",
   "nivel_accion": "AD SET",
   "formato_actual": "VIDEO",
   "formato_sugerido": null
  },
  {
   "clinica": "Laura (sedes)",
   "grupo": "sede",
   "campana": "",
   "adset": "ESPALDA",
   "anuncio": "VID _ CIATICA  _ OCT",
   "campaign_id": "",
   "adset_id": "",
   "ad_id": "",
   "gasto_7d": 3152,
   "resultados_7d": 99,
   "costo_resultado": 32,
   "tipo_resultado": "lead",
   "frecuencia": 1.39,
   "pct_nuevos": null,
   "diagnostico": "RINDE BIEN",
   "accion_sugerida": "ESCALAR — subir presupuesto",
   "detalle": "Frecuencia baja (1.39x) + costo/resultado mejor que su cuenta + volumen decente.",
   "nivel_accion": "AD SET",
   "formato_actual": "VIDEO",
   "formato_sugerido": null
  },
  {
   "clinica": "Nicolas Romero",
   "grupo": "franquicia",
   "campana": "",
   "adset": "HOMBRO",
   "anuncio": "VID_HOMBNICO_JUL",
   "campaign_id": "",
   "adset_id": "",
   "ad_id": "",
   "gasto_7d": 2355,
   "resultados_7d": 78,
   "costo_resultado": 30,
   "tipo_resultado": "lead",
   "frecuencia": 1.4,
   "pct_nuevos": null,
   "diagnostico": "RINDE BIEN",
   "accion_sugerida": "ESCALAR — subir presupuesto",
   "detalle": "Frecuencia baja (1.4x) + costo/resultado mejor que su cuenta + volumen decente.",
   "nivel_accion": "AD SET",
   "formato_actual": "VIDEO",
   "formato_sugerido": null
  },
  {
   "clinica": "Laura (sedes)",
   "grupo": "sede",
   "campana": "",
   "adset": "Espalda",
   "anuncio": "VID_ CIATICA _ SEP _ OCT - 3 OCT",
   "campaign_id": "",
   "adset_id": "",
   "ad_id": "",
   "gasto_7d": 1421,
   "resultados_7d": 69,
   "costo_resultado": 21,
   "tipo_resultado": "lead",
   "frecuencia": 1.41,
   "pct_nuevos": null,
   "diagnostico": "RINDE BIEN",
   "accion_sugerida": "ESCALAR — subir presupuesto",
   "detalle": "Frecuencia baja (1.41x) + costo/resultado mejor que su cuenta + volumen decente.",
   "nivel_accion": "AD SET",
   "formato_actual": "VIDEO",
   "formato_sugerido": null
  },
  {
   "clinica": "Queretaro",
   "grupo": "franquicia",
   "campana": "",
   "adset": "HOMBRO",
   "anuncio": "VID - HOMBRO IRVIN",
   "campaign_id": "",
   "adset_id": "",
   "ad_id": "",
   "gasto_7d": 1305,
   "resultados_7d": 82,
   "costo_resultado": 16,
   "tipo_resultado": "lead",
   "frecuencia": 1.22,
   "pct_nuevos": null,
   "diagnostico": "RINDE BIEN",
   "accion_sugerida": "ESCALAR — subir presupuesto",
   "detalle": "Frecuencia baja (1.22x) + costo/resultado mejor que su cuenta + volumen decente.",
   "nivel_accion": "AD SET",
   "formato_actual": "VIDEO",
   "formato_sugerido": null
  },
  {
   "clinica": "Laura (sedes)",
   "grupo": "sede",
   "campana": "",
   "adset": "NEUROPATIA CHECK",
   "anuncio": "VID-NEUROPATIA.SEP",
   "campaign_id": "",
   "adset_id": "",
   "ad_id": "",
   "gasto_7d": 1227,
   "resultados_7d": 45,
   "costo_resultado": 27,
   "tipo_resultado": "lead",
   "frecuencia": 1.27,
   "pct_nuevos": null,
   "diagnostico": "RINDE BIEN",
   "accion_sugerida": "ESCALAR — subir presupuesto",
   "detalle": "Frecuencia baja (1.27x) + costo/resultado mejor que su cuenta + volumen decente.",
   "nivel_accion": "AD SET",
   "formato_actual": "VIDEO",
   "formato_sugerido": null
  },
  {
   "clinica": "Gerontologia",
   "grupo": "sede",
   "campana": "",
   "adset": "BALBUENA",
   "anuncio": "VID _  Gym para personas mayores OMAR _ 08 SEP",
   "campaign_id": "",
   "adset_id": "",
   "ad_id": "",
   "gasto_7d": 1222,
   "resultados_7d": 119,
   "costo_resultado": 10,
   "tipo_resultado": "lead",
   "frecuencia": 1.38,
   "pct_nuevos": null,
   "diagnostico": "RINDE BIEN",
   "accion_sugerida": "ESCALAR — subir presupuesto",
   "detalle": "Frecuencia baja (1.38x) + costo/resultado mejor que su cuenta + volumen decente.",
   "nivel_accion": "AD SET",
   "formato_actual": "VIDEO",
   "formato_sugerido": null
  },
  {
   "clinica": "Laura (sedes)",
   "grupo": "sede",
   "campana": "",
   "adset": "Tropicalizados",
   "anuncio": "VID _  RODILLA _ TROPICALIZADO",
   "campaign_id": "",
   "adset_id": "",
   "ad_id": "",
   "gasto_7d": 1157,
   "resultados_7d": 35,
   "costo_resultado": 33,
   "tipo_resultado": "lead",
   "frecuencia": 1.23,
   "pct_nuevos": null,
   "diagnostico": "RINDE BIEN",
   "accion_sugerida": "ESCALAR — subir presupuesto",
   "detalle": "Frecuencia baja (1.23x) + costo/resultado mejor que su cuenta + volumen decente.",
   "nivel_accion": "AD SET",
   "formato_actual": "VIDEO",
   "formato_sugerido": null
  },
  {
   "clinica": "Gerontologia",
   "grupo": "sede",
   "campana": "",
   "adset": "Coacalco",
   "anuncio": "VID_CONSULTA_GE _ NUEVO - Copia",
   "campaign_id": "",
   "adset_id": "",
   "ad_id": "",
   "gasto_7d": 1097,
   "resultados_7d": 61,
   "costo_resultado": 18,
   "tipo_resultado": "lead",
   "frecuencia": 1.26,
   "pct_nuevos": null,
   "diagnostico": "RINDE BIEN",
   "accion_sugerida": "ESCALAR — subir presupuesto",
   "detalle": "Frecuencia baja (1.26x) + costo/resultado mejor que su cuenta + volumen decente.",
   "nivel_accion": "AD SET",
   "formato_actual": "VIDEO",
   "formato_sugerido": null
  },
  {
   "clinica": "Promo/Compl.",
   "grupo": "sede",
   "campana": "",
   "adset": "Neuropatia",
   "anuncio": "VID - NEURO SINTOMAS - OCT",
   "campaign_id": "",
   "adset_id": "",
   "ad_id": "",
   "gasto_7d": 1070,
   "resultados_7d": 50,
   "costo_resultado": 21,
   "tipo_resultado": "lead",
   "frecuencia": 1.43,
   "pct_nuevos": null,
   "diagnostico": "RINDE BIEN",
   "accion_sugerida": "ESCALAR — subir presupuesto",
   "detalle": "Frecuencia baja (1.43x) + costo/resultado mejor que su cuenta + volumen decente.",
   "nivel_accion": "AD SET",
   "formato_actual": "VIDEO",
   "formato_sugerido": null
  },
  {
   "clinica": "Valle Dorado",
   "grupo": "franquicia",
   "campana": "",
   "adset": "ESPALDA",
   "anuncio": "VID_QUIRO ESPALDA",
   "campaign_id": "",
   "adset_id": "",
   "ad_id": "",
   "gasto_7d": 1066,
   "resultados_7d": 35,
   "costo_resultado": 30,
   "tipo_resultado": "lead",
   "frecuencia": 1.2,
   "pct_nuevos": null,
   "diagnostico": "RINDE BIEN",
   "accion_sugerida": "ESCALAR — subir presupuesto",
   "detalle": "Frecuencia baja (1.2x) + costo/resultado mejor que su cuenta + volumen decente.",
   "nivel_accion": "AD SET",
   "formato_actual": "VIDEO",
   "formato_sugerido": null
  },
  {
   "clinica": "Queretaro",
   "grupo": "franquicia",
   "campana": "",
   "adset": "Publicación: \"Trata tu neuropatía de forma segura y con...\"",
   "anuncio": "Publicación: \"Trata tu neuropatía de forma segura y con...\"",
   "campaign_id": "",
   "adset_id": "",
   "ad_id": "",
   "gasto_7d": 1021,
   "resultados_7d": 50,
   "costo_resultado": 20,
   "tipo_resultado": "lead",
   "frecuencia": 1.58,
   "pct_nuevos": null,
   "diagnostico": "RINDE BIEN",
   "accion_sugerida": "ESCALAR — subir presupuesto",
   "detalle": "Frecuencia baja (1.58x) + costo/resultado mejor que su cuenta + volumen decente.",
   "nivel_accion": "AD SET",
   "formato_actual": "OTRO",
   "formato_sugerido": null
  },
  {
   "clinica": "Cuautitlan",
   "grupo": "franquicia",
   "campana": "",
   "adset": "Directo",
   "anuncio": "VID_QUIRO _ 1 ABRIL - Copia 2",
   "campaign_id": "",
   "adset_id": "",
   "ad_id": "",
   "gasto_7d": 937,
   "resultados_7d": 53,
   "costo_resultado": 18,
   "tipo_resultado": "lead",
   "frecuencia": 1.23,
   "pct_nuevos": null,
   "diagnostico": "RINDE BIEN",
   "accion_sugerida": "ESCALAR — subir presupuesto",
   "detalle": "Frecuencia baja (1.23x) + costo/resultado mejor que su cuenta + volumen decente.",
   "nivel_accion": "AD SET",
   "formato_actual": "VIDEO",
   "formato_sugerido": null
  },
  {
   "clinica": "Gerontologia",
   "grupo": "sede",
   "campana": "",
   "adset": "Imagen Gerontologia - NEZA",
   "anuncio": "NEZA DOMINGOS",
   "campaign_id": "",
   "adset_id": "",
   "ad_id": "",
   "gasto_7d": 750,
   "resultados_7d": 137,
   "costo_resultado": 5,
   "tipo_resultado": "lead",
   "frecuencia": 1.43,
   "pct_nuevos": null,
   "diagnostico": "RINDE BIEN",
   "accion_sugerida": "ESCALAR — subir presupuesto",
   "detalle": "Frecuencia baja (1.43x) + costo/resultado mejor que su cuenta + volumen decente.",
   "nivel_accion": "AD SET",
   "formato_actual": "OTRO",
   "formato_sugerido": null
  },
  {
   "clinica": "Queretaro",
   "grupo": "franquicia",
   "campana": "",
   "adset": "NEUROPATIA",
   "anuncio": "VID - NEURO MARY",
   "campaign_id": "",
   "adset_id": "",
   "ad_id": "",
   "gasto_7d": 723,
   "resultados_7d": 39,
   "costo_resultado": 19,
   "tipo_resultado": "lead",
   "frecuencia": 1.46,
   "pct_nuevos": null,
   "diagnostico": "RINDE BIEN",
   "accion_sugerida": "ESCALAR — subir presupuesto",
   "detalle": "Frecuencia baja (1.46x) + costo/resultado mejor que su cuenta + volumen decente.",
   "nivel_accion": "AD SET",
   "formato_actual": "VIDEO",
   "formato_sugerido": null
  },
  {
   "clinica": "Cuautla",
   "grupo": "franquicia",
   "campana": "",
   "adset": "Neuropatia",
   "anuncio": "NEUROPATIA MARY",
   "campaign_id": "",
   "adset_id": "",
   "ad_id": "",
   "gasto_7d": 683,
   "resultados_7d": 23,
   "costo_resultado": 30,
   "tipo_resultado": "lead",
   "frecuencia": 1.56,
   "pct_nuevos": null,
   "diagnostico": "RINDE BIEN",
   "accion_sugerida": "ESCALAR — subir presupuesto",
   "detalle": "Frecuencia baja (1.56x) + costo/resultado mejor que su cuenta + volumen decente.",
   "nivel_accion": "AD SET",
   "formato_actual": "OTRO",
   "formato_sugerido": null
  },
  {
   "clinica": "Cuautitlan",
   "grupo": "franquicia",
   "campana": "",
   "adset": "Directo",
   "anuncio": "VID _ NEUROPATIA  01 ABRIL - Copia",
   "campaign_id": "",
   "adset_id": "",
   "ad_id": "",
   "gasto_7d": 656,
   "resultados_7d": 28,
   "costo_resultado": 23,
   "tipo_resultado": "lead",
   "frecuencia": 1.28,
   "pct_nuevos": null,
   "diagnostico": "RINDE BIEN",
   "accion_sugerida": "ESCALAR — subir presupuesto",
   "detalle": "Frecuencia baja (1.28x) + costo/resultado mejor que su cuenta + volumen decente.",
   "nivel_accion": "AD SET",
   "formato_actual": "VIDEO",
   "formato_sugerido": null
  },
  {
   "clinica": "Claveria",
   "grupo": "franquicia",
   "campana": "",
   "adset": "RODILLA - CHECK",
   "anuncio": "VID _ RODILLA SINTOMAS  _ OCT",
   "campaign_id": "",
   "adset_id": "",
   "ad_id": "",
   "gasto_7d": 607,
   "resultados_7d": 24,
   "costo_resultado": 25,
   "tipo_resultado": "lead",
   "frecuencia": 1.26,
   "pct_nuevos": null,
   "diagnostico": "RINDE BIEN",
   "accion_sugerida": "ESCALAR — subir presupuesto",
   "detalle": "Frecuencia baja (1.26x) + costo/resultado mejor que su cuenta + volumen decente.",
   "nivel_accion": "AD SET",
   "formato_actual": "VIDEO",
   "formato_sugerido": null
  },
  {
   "clinica": "Laura (sedes)",
   "grupo": "sede",
   "campana": "",
   "adset": "Neuropatia",
   "anuncio": "VID_ NEUROPATIA DIABETICA _ SEP _ OCT",
   "campaign_id": "",
   "adset_id": "",
   "ad_id": "",
   "gasto_7d": 570,
   "resultados_7d": 27,
   "costo_resultado": 21,
   "tipo_resultado": "lead",
   "frecuencia": 1.59,
   "pct_nuevos": null,
   "diagnostico": "RINDE BIEN",
   "accion_sugerida": "ESCALAR — subir presupuesto",
   "detalle": "Frecuencia baja (1.59x) + costo/resultado mejor que su cuenta + volumen decente.",
   "nivel_accion": "AD SET",
   "formato_actual": "VIDEO",
   "formato_sugerido": null
  },
  {
   "clinica": "Tepeyac",
   "grupo": "franquicia",
   "campana": "",
   "adset": "Espalda",
   "anuncio": "VID - CIATICA LUMBALGIA - JUN",
   "campaign_id": "",
   "adset_id": "",
   "ad_id": "",
   "gasto_7d": 503,
   "resultados_7d": 16,
   "costo_resultado": 31,
   "tipo_resultado": "lead",
   "frecuencia": 1.49,
   "pct_nuevos": null,
   "diagnostico": "RINDE BIEN",
   "accion_sugerida": "ESCALAR — subir presupuesto",
   "detalle": "Frecuencia baja (1.49x) + costo/resultado mejor que su cuenta + volumen decente.",
   "nivel_accion": "AD SET",
   "formato_actual": "VIDEO",
   "formato_sugerido": null
  }
 ],
 "resumen": {
  "n_apagar": 0,
  "n_cambiar_publico": 0,
  "n_contenido_nuevo": 0,
  "n_vigilar": 0,
  "n_escalar": 25,
  "gasto_liberable_estimado_dia": 0
 }
};
