window.FATIGA_DATA = {
 "actualizado": "29/09/2026 05:02",
 "periodo": "2026-09-01 a 2026-09-29",
 "diagnostico": [
  {
   "cuenta": "San Juan del Rio",
   "adset": "Publicación: \"Atención zona San Juan del Río. 📍\"",
   "veredicto": "RENOVAR PUBLICO",
   "freq": 2.36,
   "gasto": 10709,
   "leads": 229,
   "cpl": 47,
   "pct_nuevos": 18,
   "cpm1": 30,
   "cpm2": 33
  },
  {
   "cuenta": "Promo/Compl.",
   "adset": "Publicación: \"¿Vives con dolor en Ecatepec? 📍\"",
   "veredicto": "RENOVAR PUBLICO",
   "freq": 2.3,
   "gasto": 55524,
   "leads": 915,
   "cpl": 61,
   "pct_nuevos": 19,
   "cpm1": 40,
   "cpm2": 40
  },
  {
   "cuenta": "Promo/Compl.",
   "adset": "Publicación: \"¡Que el dolor no te apague el grito este...\"",
   "veredicto": "RENOVAR PUBLICO",
   "freq": 2.16,
   "gasto": 14776,
   "leads": 248,
   "cpl": 60,
   "pct_nuevos": 19,
   "cpm1": 66,
   "cpm2": 80
  },
  {
   "cuenta": "Valle Dorado",
   "adset": "NEUROPATIA",
   "veredicto": "PUBLICO CANSANDOSE",
   "freq": 2.11,
   "gasto": 3422,
   "leads": 55,
   "cpl": 62,
   "pct_nuevos": 35,
   "cpm1": 47,
   "cpm2": 68
  },
  {
   "cuenta": "Promo/Compl.",
   "adset": "Publicación: \"¿Dolor de espalda al agacharte?\"",
   "veredicto": "PUBLICO CANSANDOSE",
   "freq": 2.05,
   "gasto": 14260,
   "leads": 241,
   "cpl": 59,
   "pct_nuevos": 22,
   "cpm1": 27,
   "cpm2": 38
  },
  {
   "cuenta": "Ajusco",
   "adset": "ESP",
   "veredicto": "PUBLICO CANSANDOSE",
   "freq": 1.8,
   "gasto": 4411,
   "leads": 66,
   "cpl": 67,
   "pct_nuevos": 21,
   "cpm1": 58,
   "cpm2": 95
  },
  {
   "cuenta": "Tepeyac",
   "adset": "MIX",
   "veredicto": "PUBLICO CANSANDOSE",
   "freq": 1.77,
   "gasto": 3142,
   "leads": 82,
   "cpl": 38,
   "pct_nuevos": 34,
   "cpm1": 23,
   "cpm2": 33
  },
  {
   "cuenta": "Claveria",
   "adset": "NEUROPATIA - CHECK",
   "veredicto": "PUBLICO CANSANDOSE",
   "freq": 1.7,
   "gasto": 2276,
   "leads": 75,
   "cpl": 30,
   "pct_nuevos": 13,
   "cpm1": 50,
   "cpm2": 72
  },
  {
   "cuenta": "Laura (sedes)",
   "adset": "ESPALDA",
   "veredicto": "CAMBIAR CREATIVO",
   "freq": 3.53,
   "gasto": 42008,
   "leads": 1685,
   "cpl": 25,
   "pct_nuevos": 342,
   "cpm1": 27,
   "cpm2": 23
  },
  {
   "cuenta": "Promo/Compl.",
   "adset": "Publicación: \"📍 ¿Vives en Milpa Alta y el dolor de rodilla ya...\"",
   "veredicto": "CAMBIAR CREATIVO",
   "freq": 3.2,
   "gasto": 41341,
   "leads": 843,
   "cpl": 49,
   "pct_nuevos": 65,
   "cpm1": 22,
   "cpm2": 25
  },
  {
   "cuenta": "Nicolas Romero",
   "adset": "Publicación: \"¡Atención, Nicolás Romero! ¿Buscas terapia de...\"",
   "veredicto": "CAMBIAR CREATIVO",
   "freq": 3.1,
   "gasto": 20522,
   "leads": 366,
   "cpl": 56,
   "pct_nuevos": 46,
   "cpm1": 28,
   "cpm2": 30
  },
  {
   "cuenta": "Promo/Compl.",
   "adset": "Publicación: \"En Equilibrio Total seguimos creciendo y buscamos...\"",
   "veredicto": "CAMBIAR CREATIVO",
   "freq": 3.06,
   "gasto": 3246,
   "leads": 30,
   "cpl": 108,
   "pct_nuevos": null,
   "cpm1": null,
   "cpm2": null
  },
  {
   "cuenta": "Cuautla",
   "adset": "Publicación: \"¿Te duele el hombro, la espalda o la rodilla? 😖\"",
   "veredicto": "CAMBIAR CREATIVO",
   "freq": 3.03,
   "gasto": 14472,
   "leads": 462,
   "cpl": 31,
   "pct_nuevos": 40,
   "cpm1": 19,
   "cpm2": 24
  },
  {
   "cuenta": "Queretaro",
   "adset": "NEUROPATIA",
   "veredicto": "CAMBIAR CREATIVO",
   "freq": 2.97,
   "gasto": 4421,
   "leads": 249,
   "cpl": 18,
   "pct_nuevos": 41,
   "cpm1": 51,
   "cpm2": 44
  },
  {
   "cuenta": "Laura (sedes)",
   "adset": "Neuropatia",
   "veredicto": "CAMBIAR CREATIVO",
   "freq": 2.84,
   "gasto": 3719,
   "leads": 77,
   "cpl": 48,
   "pct_nuevos": 274,
   "cpm1": 31,
   "cpm2": 30
  },
  {
   "cuenta": "Laura (sedes)",
   "adset": "Rodilla",
   "veredicto": "CAMBIAR CREATIVO",
   "freq": 2.81,
   "gasto": 3993,
   "leads": 92,
   "cpl": 43,
   "pct_nuevos": 410,
   "cpm1": 25,
   "cpm2": 25
  },
  {
   "cuenta": "Pachuca",
   "adset": "NEUROPATÍA",
   "veredicto": "CAMBIAR CREATIVO",
   "freq": 2.8,
   "gasto": 1817,
   "leads": 40,
   "cpl": 45,
   "pct_nuevos": 72,
   "cpm1": 39,
   "cpm2": 46
  },
  {
   "cuenta": "San Juan del Rio",
   "adset": "Neuropatia - Check",
   "veredicto": "CAMBIAR CREATIVO",
   "freq": 2.78,
   "gasto": 1072,
   "leads": 27,
   "cpl": 40,
   "pct_nuevos": 80,
   "cpm1": 37,
   "cpm2": 37
  },
  {
   "cuenta": "Promo/Compl.",
   "adset": "Publicación: \"Si eres de Plaza Neza, 📍\"",
   "veredicto": "CAMBIAR CREATIVO",
   "freq": 2.74,
   "gasto": 37012,
   "leads": 759,
   "cpl": 49,
   "pct_nuevos": 52,
   "cpm1": 35,
   "cpm2": 37
  },
  {
   "cuenta": "Queretaro",
   "adset": "RODILLA",
   "veredicto": "CAMBIAR CREATIVO",
   "freq": 2.6,
   "gasto": 634,
   "leads": 42,
   "cpl": 15,
   "pct_nuevos": 24,
   "cpm1": 50,
   "cpm2": 56
  },
  {
   "cuenta": "Cuautla",
   "adset": "Neuropatia",
   "veredicto": "CAMBIAR CREATIVO",
   "freq": 2.54,
   "gasto": 3452,
   "leads": 143,
   "cpl": 24,
   "pct_nuevos": 54,
   "cpm1": 25,
   "cpm2": 27
  },
  {
   "cuenta": "Ajusco",
   "adset": "NEU",
   "veredicto": "CAMBIAR CREATIVO",
   "freq": 2.53,
   "gasto": 3917,
   "leads": 68,
   "cpl": 58,
   "pct_nuevos": 95,
   "cpm1": 67,
   "cpm2": 89
  },
  {
   "cuenta": "Cuautla",
   "adset": "Rodilla",
   "veredicto": "CAMBIAR CREATIVO",
   "freq": 2.5,
   "gasto": 836,
   "leads": 25,
   "cpl": 33,
   "pct_nuevos": 44,
   "cpm1": 31,
   "cpm2": 31
  },
  {
   "cuenta": "Laura (sedes)",
   "adset": "Servicios / Testimonios",
   "veredicto": "VIGILAR",
   "freq": 2.5,
   "gasto": 1649,
   "leads": 26,
   "cpl": 63,
   "pct_nuevos": 146,
   "cpm1": 29,
   "cpm2": 35
  },
  {
   "cuenta": "Laura (sedes)",
   "adset": "RODILLA",
   "veredicto": "VIGILAR",
   "freq": 2.48,
   "gasto": 4395,
   "leads": 173,
   "cpl": 25,
   "pct_nuevos": 432,
   "cpm1": 60,
   "cpm2": 40
  },
  {
   "cuenta": "Promo/Compl.",
   "adset": "Publicación: \"El dolor articular no desaparece solo. Actúa y...\"",
   "veredicto": "VIGILAR",
   "freq": 2.43,
   "gasto": 21530,
   "leads": 362,
   "cpl": 59,
   "pct_nuevos": 50,
   "cpm1": 32,
   "cpm2": 39
  },
  {
   "cuenta": "Ajusco",
   "adset": "ROD",
   "veredicto": "VIGILAR",
   "freq": 2.43,
   "gasto": 8012,
   "leads": 109,
   "cpl": 74,
   "pct_nuevos": 60,
   "cpm1": 56,
   "cpm2": 67
  },
  {
   "cuenta": "Promo/Compl.",
   "adset": "Publicación: \"Si eres de Mixquiahuala Hidalgo, 📍\"",
   "veredicto": "VIGILAR",
   "freq": 2.41,
   "gasto": 11113,
   "leads": 292,
   "cpl": 38,
   "pct_nuevos": 77,
   "cpm1": 24,
   "cpm2": 23
  },
  {
   "cuenta": "San Juan del Rio",
   "adset": "Publicación: \"🏥 Conoce Equilibrio Total San Juan del Río, tu...\"",
   "veredicto": "VIGILAR",
   "freq": 2.4,
   "gasto": 5503,
   "leads": 188,
   "cpl": 29,
   "pct_nuevos": 266,
   "cpm1": 35,
   "cpm2": 26
  },
  {
   "cuenta": "Cuautitlan",
   "adset": "Directo",
   "veredicto": "VIGILAR",
   "freq": 2.39,
   "gasto": 13485,
   "leads": 724,
   "cpl": 19,
   "pct_nuevos": 64,
   "cpm1": 36,
   "cpm2": 45
  },
  {
   "cuenta": "Laura (sedes)",
   "adset": "Publico Nuevo (radio 10km, edad 22-65)",
   "veredicto": "VIGILAR",
   "freq": 2.36,
   "gasto": 3120,
   "leads": 82,
   "cpl": 38,
   "pct_nuevos": 264,
   "cpm1": 25,
   "cpm2": 31
  },
  {
   "cuenta": "Promo/Compl.",
   "adset": "Publicación: \"En Equilibrio Total seguimos creciendo y buscamos...\"",
   "veredicto": "VIGILAR",
   "freq": 2.36,
   "gasto": 2684,
   "leads": 36,
   "cpl": 75,
   "pct_nuevos": null,
   "cpm1": null,
   "cpm2": null
  },
  {
   "cuenta": "Nicolas Romero",
   "adset": "RODILLA",
   "veredicto": "VIGILAR",
   "freq": 2.35,
   "gasto": 7644,
   "leads": 242,
   "cpl": 32,
   "pct_nuevos": 40,
   "cpm1": 21,
   "cpm2": 22
  },
  {
   "cuenta": "Laura (sedes)",
   "adset": "NEUROPATIA",
   "veredicto": "VIGILAR",
   "freq": 2.33,
   "gasto": 13391,
   "leads": 436,
   "cpl": 31,
   "pct_nuevos": 126,
   "cpm1": 42,
   "cpm2": 39
  },
  {
   "cuenta": "Laura (sedes)",
   "adset": "NEUROPATIA",
   "veredicto": "VIGILAR",
   "freq": 2.32,
   "gasto": 6936,
   "leads": 173,
   "cpl": 40,
   "pct_nuevos": 38,
   "cpm1": 32,
   "cpm2": 35
  },
  {
   "cuenta": "Pachuca",
   "adset": "RODILLA",
   "veredicto": "VIGILAR",
   "freq": 2.3,
   "gasto": 4533,
   "leads": 120,
   "cpl": 38,
   "pct_nuevos": 41,
   "cpm1": 32,
   "cpm2": 32
  },
  {
   "cuenta": "Laura (sedes)",
   "adset": "Hombro",
   "veredicto": "VIGILAR",
   "freq": 2.29,
   "gasto": 8693,
   "leads": 220,
   "cpl": 40,
   "pct_nuevos": 154,
   "cpm1": 27,
   "cpm2": 30
  },
  {
   "cuenta": "Nicolas Romero",
   "adset": "ESPALDA",
   "veredicto": "VIGILAR",
   "freq": 2.28,
   "gasto": 4112,
   "leads": 66,
   "cpl": 62,
   "pct_nuevos": 41,
   "cpm1": 25,
   "cpm2": 28
  },
  {
   "cuenta": "Nicolas Romero",
   "adset": "HOMBRO",
   "veredicto": "VIGILAR",
   "freq": 2.24,
   "gasto": 8890,
   "leads": 381,
   "cpl": 23,
   "pct_nuevos": 51,
   "cpm1": 23,
   "cpm2": 21
  },
  {
   "cuenta": "Tepeyac",
   "adset": "Espalda",
   "veredicto": "VIGILAR",
   "freq": 2.22,
   "gasto": 8083,
   "leads": 265,
   "cpl": 31,
   "pct_nuevos": 91,
   "cpm1": 63,
   "cpm2": 78
  }
 ],
 "exitosos": [
  {
   "cuenta": "Gerontologia",
   "ad": "VID _  Gym para personas mayores OMAR _ 08 SEP",
   "adset": "NEZA",
   "freq": 1.99,
   "gasto": 886,
   "leads": 115,
   "cpl": 8
  },
  {
   "cuenta": "Xochimilco",
   "ad": "Publicación: \"🌿 En Equilibrio Total Xochimilco llevamos años...\"",
   "adset": "Publicación: \"🌿 En Equilibrio Total Xochimilco llevamos años...\"",
   "freq": 1.43,
   "gasto": 1891,
   "leads": 175,
   "cpl": 11
  },
  {
   "cuenta": "Promo/Compl.",
   "ad": "Neuropatia",
   "adset": "ORGANICO PAUTA",
   "freq": 1.88,
   "gasto": 12767,
   "leads": 946,
   "cpl": 13
  },
  {
   "cuenta": "Promo/Compl.",
   "ad": "Neuropatia",
   "adset": "ORGANICO PAUTA",
   "freq": 1.55,
   "gasto": 5757,
   "leads": 378,
   "cpl": 15
  },
  {
   "cuenta": "Promo/Compl.",
   "ad": "VID - NEURO PADECIMIENTO - OCT",
   "adset": "Neuropatia",
   "freq": 1.53,
   "gasto": 847,
   "leads": 55,
   "cpl": 15
  },
  {
   "cuenta": "Cuautitlan",
   "ad": "VID _ NEUROPATIA  01 ABRIL - Copia",
   "adset": "Directo",
   "freq": 1.34,
   "gasto": 844,
   "leads": 58,
   "cpl": 15
  },
  {
   "cuenta": "Queretaro",
   "ad": "VID - HOMBRO IRVIN",
   "adset": "HOMBRO",
   "freq": 1.53,
   "gasto": 3818,
   "leads": 237,
   "cpl": 16
  },
  {
   "cuenta": "Cuautitlan",
   "ad": "VID_QUIRO _ 1 ABRIL - Copia 2",
   "adset": "Directo",
   "freq": 1.28,
   "gasto": 1157,
   "leads": 67,
   "cpl": 17
  },
  {
   "cuenta": "Promo/Compl.",
   "ad": "VID - ACUPUNTURA JUN",
   "adset": "ORGANICO PAUTA",
   "freq": 1.73,
   "gasto": 2594,
   "leads": 144,
   "cpl": 18
  },
  {
   "cuenta": "Queretaro",
   "ad": "VID - HOMBRO DOLOROSO JUN",
   "adset": "HOMBRO",
   "freq": 1.5,
   "gasto": 1303,
   "leads": 72,
   "cpl": 18
  },
  {
   "cuenta": "Promo/Compl.",
   "ad": "Neuropatia - Copia",
   "adset": "PROMOCIONES CDMX",
   "freq": 1.52,
   "gasto": 10572,
   "leads": 550,
   "cpl": 19
  },
  {
   "cuenta": "Gerontologia",
   "ad": "VID_CONSULTA_GE _ NUEVO - Copia",
   "adset": "Coacalco",
   "freq": 1.69,
   "gasto": 2417,
   "leads": 130,
   "cpl": 19
  },
  {
   "cuenta": "Claveria",
   "ad": "VID _ PADECIMIENTO RODILLA _ OCT",
   "adset": "RODILLA - CHECK",
   "freq": 1.45,
   "gasto": 2328,
   "leads": 107,
   "cpl": 22
  },
  {
   "cuenta": "Laura (sedes)",
   "ad": "EST - NEUROPATIA V3 JUL",
   "adset": "NEUROPATIA",
   "freq": 1.88,
   "gasto": 977,
   "leads": 42,
   "cpl": 23
  },
  {
   "cuenta": "Gerontologia",
   "ad": "VID_CONSULTA_GE _ NUEVO",
   "adset": "Balbuena",
   "freq": 1.89,
   "gasto": 4751,
   "leads": 205,
   "cpl": 23
  },
  {
   "cuenta": "Valle Dorado",
   "ad": "VID _ PADECIMIENTO _ SEP",
   "adset": "HOMBRO",
   "freq": 1.6,
   "gasto": 3260,
   "leads": 143,
   "cpl": 23
  },
  {
   "cuenta": "Laura (sedes)",
   "ad": "VID  _ NEUROPATIA DIABETICA _ OCT",
   "adset": "Neuropatia",
   "freq": 1.88,
   "gasto": 2905,
   "leads": 121,
   "cpl": 24
  },
  {
   "cuenta": "Promo/Compl.",
   "ad": "VID - ACUPUNTURA JUN",
   "adset": "ORGANICO PAUTA",
   "freq": 1.6,
   "gasto": 1984,
   "leads": 81,
   "cpl": 24
  },
  {
   "cuenta": "La Moderna",
   "ad": "VID_ ESPALDA SINTOMAS _SEP",
   "adset": "Espalda",
   "freq": 1.45,
   "gasto": 2047,
   "leads": 86,
   "cpl": 24
  },
  {
   "cuenta": "Laura (sedes)",
   "ad": "VID - NEUROPATIA DIABETICA 3 JUN",
   "adset": "NEUROPATIA",
   "freq": 1.49,
   "gasto": 569,
   "leads": 23,
   "cpl": 25
  },
  {
   "cuenta": "Pachuca",
   "ad": "Anuncio Campaña de mensajes personalizada 8/8/2026",
   "adset": "Conjunto de anuncios Campaña de mensajes personalizada 8/8/2026",
   "freq": 1.93,
   "gasto": 15135,
   "leads": 608,
   "cpl": 25
  },
  {
   "cuenta": "Promo/Compl.",
   "ad": "FEED",
   "adset": "PROMOCIONES CDMX",
   "freq": 1.59,
   "gasto": 17862,
   "leads": 697,
   "cpl": 26
  },
  {
   "cuenta": "Cuautla",
   "ad": "VID - ESPALDA GABO V1 JUN",
   "adset": "Espalda",
   "freq": 1.64,
   "gasto": 844,
   "leads": 32,
   "cpl": 26
  },
  {
   "cuenta": "Laura (sedes)",
   "ad": "VID _ NEUROPATIA DIABETICA _ OCT",
   "adset": "NEUROPATIA",
   "freq": 1.48,
   "gasto": 3316,
   "leads": 125,
   "cpl": 27
  },
  {
   "cuenta": "Cuautla",
   "ad": "Publicación: \"Vivir con dolor no es normal. 🛑\"",
   "adset": "Publicación: \"Vivir con dolor no es normal. 🛑\"",
   "freq": 1.98,
   "gasto": 6100,
   "leads": 228,
   "cpl": 27
  }
 ],
 "sin_leads": []
};
